-- =============================================================================
-- AI English Tutor - Stage 4 Exercises Database Schema
-- =============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- STAGE 4 EXERCISE 1: OPINION EXPRESSION & DEBATE
-- =============================================================================

-- Table for Opinion Expression & Debate
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage4_exercise1_opinion_debate (
    id SERIAL PRIMARY KEY,
    topic TEXT NOT NULL,
    topic_urdu TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'b2_upper_intermediate',
    speaking_duration TEXT NOT NULL,
    thinking_time TEXT NOT NULL,
    expected_structure TEXT NOT NULL,
    key_connectors TEXT[] NOT NULL,
    key_connectors_urdu TEXT[] NOT NULL,
    vocabulary_focus TEXT[] NOT NULL,
    vocabulary_focus_urdu TEXT[] NOT NULL,
    model_response TEXT NOT NULL,
    model_response_urdu TEXT NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    learning_objectives TEXT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for Opinion Expression & Debate
INSERT INTO public.ai_tutor_stage4_exercise1_opinion_debate (topic, topic_urdu, category, difficulty, speaking_duration, thinking_time, expected_structure, key_connectors, key_connectors_urdu, vocabulary_focus, vocabulary_focus_urdu, model_response, model_response_urdu, evaluation_criteria, learning_objectives) VALUES
('Is social media making people more connected or more isolated?', 'کیا سوشل میڈیا لوگوں کو زیادہ جڑا ہوا یا زیادہ الگ تھلگ بنا رہا ہے؟', 'technology_society', 'b2_upper_intermediate', '60-90_seconds', '10_seconds', 'opinion_supporting_arguments_counter_arguments_conclusion', ARRAY['however', 'although', 'on the other hand', 'furthermore', 'nevertheless', 'in contrast', 'additionally'], ARRAY['تاہم', 'اگرچہ', 'دوسری طرف', 'مزید برآں', 'بہر حال', 'اس کے برعکس', 'اس کے علاوہ'], ARRAY['connected', 'isolated', 'online', 'friendships', 'face-to-face', 'virtual', 'relationships', 'communication'], ARRAY['جڑا ہوا', 'الگ تھلگ', 'آن لائن', 'دوستیاں', 'آمنے سامنے', 'مجازی', 'تعلقات', 'مواصلات'], 'I believe social media is making people more connected in some ways, but also more isolated in others. On the one hand, it allows us to stay in touch with friends and family across the world, and we can share our lives instantly. However, I think it''s also creating a sense of isolation because people are spending less time having real face-to-face conversations. Furthermore, many people compare their lives to others'' carefully curated posts, which can lead to feelings of loneliness. Nevertheless, I think the key is finding a balance between online and offline interactions.', 'میں سمجھتا ہوں کہ سوشل میڈیا کچھ طریقوں سے لوگوں کو زیادہ جڑا ہوا بنا رہا ہے، لیکن دوسرے طریقوں سے زیادہ الگ تھلگ بھی۔ ایک طرف، یہ ہمیں دنیا بھر میں دوستوں اور خاندان سے رابطے میں رہنے کی اجازت دیتا ہے، اور ہم اپنی زندگیاں فوراً شیئر کر سکتے ہیں۔ تاہم، میں سمجھتا ہوں کہ یہ تنہائی کا احساس بھی پیدا کر رہا ہے کیونکہ لوگ حقیقی آمنے سامنے کی گفتگو میں کم وقت گزار رہے ہیں۔ مزید برآں، بہت سے لوگ اپنی زندگیوں کا موازنہ دوسروں کے احتیاط سے تیار کردہ پوسٹس سے کرتے ہیں، جو تنہائی کے احساسات کا باعث بن سکتا ہے۔ بہر حال، میں سمجھتا ہوں کہ کلید آن لائن اور آف لائن تعاملات کے درمیان توازن تلاش کرنا ہے۔', '{"opinion_clarity": ["clear_position", "balanced_view", "personal_insight"], "connector_usage": ["however", "although", "on_the_other_hand", "furthermore", "nevertheless"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "natural_flow", "minimal_pauses"], "grammar_accuracy": ["complex_sentences", "conditional_structures", "passive_voice", "modals"], "lexical_richness": ["academic_vocabulary", "synonyms", "collocations", "idiomatic_expressions"], "coherence_structure": ["logical_organization", "supporting_arguments", "counter_arguments", "conclusion"], "minimum_score": 80}', ARRAY['Express and defend complex opinions on abstract topics', 'Use transitional phrases and connectors effectively', 'Develop fluency in extended monologue speaking', 'Build confidence in public speaking and structured expression', 'Enhance academic and opinionated vocabulary usage']),
('Should students be allowed to use phones in school?', 'کیا طلباء کو سکول میں فون استعمال کرنے کی اجازت ہونی چاہیے؟', 'education_technology', 'b2_upper_intermediate', '60-90_seconds', '10_seconds', 'opinion_supporting_arguments_counter_arguments_conclusion', ARRAY['however', 'although', 'on the other hand', 'furthermore', 'nevertheless', 'in contrast', 'additionally'], ARRAY['تاہم', 'اگرچہ', 'دوسری طرف', 'مزید برآں', 'بہر حال', 'اس کے برعکس', 'اس کے علاوہ'], ARRAY['distraction', 'education', 'benefits', 'rules', 'focus', 'learning', 'technology', 'discipline'], ARRAY['توجہ ہٹانا', 'تعلیم', 'فوائد', 'قوانین', 'توجہ', 'سیکھنا', 'ٹیکنالوجی', 'نظم و ضبط'], 'I think students should be allowed to use phones in school, but with clear restrictions. On the one hand, phones can be valuable educational tools for research, accessing digital textbooks, and using educational apps. However, they can also be major distractions during class time. Furthermore, phones can help with communication in emergencies and allow parents to stay connected with their children. Nevertheless, I believe schools should implement strict rules about when and how phones can be used, perhaps only during breaks or for specific educational purposes. The key is finding the right balance between leveraging technology for learning while maintaining focus in the classroom.', 'میں سمجھتا ہوں کہ طلباء کو سکول میں فون استعمال کرنے کی اجازت ہونی چاہیے، لیکن واضح پابندیوں کے ساتھ۔ ایک طرف، فون تحقیق، ڈیجیٹل ٹیکسٹ بکس تک رسائی، اور تعلیمی ایپس استعمال کرنے کے لیے قیمتی تعلیمی اوزار ہو سکتے ہیں۔ تاہم، وہ کلاس کے وقت میں بڑی توجہ ہٹانے کا باعث بھی ہو سکتے ہیں۔ مزید برآں، فون ہنگامی حالات میں مواصلات میں مدد کر سکتے ہیں اور والدین کو اپنے بچوں سے جڑے رہنے کی اجازت دیتے ہیں۔ بہر حال، میں سمجھتا ہوں کہ سکولوں کو فون کے استعمال کے بارے میں سخت قوانین نافذ کرنے چاہئیں، شاید صرف وقفوں کے دوران یا مخصوص تعلیمی مقاصد کے لیے۔ کلید سیکھنے کے لیے ٹیکنالوجی کا فائدہ اٹھانے اور کلاس روم میں توجہ برقرار رکھنے کے درمیان صحیح توازن تلاش کرنا ہے۔', '{"opinion_clarity": ["clear_position", "balanced_view", "personal_insight"], "connector_usage": ["however", "although", "on_the_other_hand", "furthermore", "nevertheless"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "natural_flow", "minimal_pauses"], "grammar_accuracy": ["complex_sentences", "conditional_structures", "passive_voice", "modals"], "lexical_richness": ["academic_vocabulary", "synonyms", "collocations", "idiomatic_expressions"], "coherence_structure": ["logical_organization", "supporting_arguments", "counter_arguments", "conclusion"], "minimum_score": 80}', ARRAY['Express and defend complex opinions on abstract topics', 'Use transitional phrases and connectors effectively', 'Develop fluency in extended monologue speaking', 'Build confidence in public speaking and structured expression', 'Enhance academic and opinionated vocabulary usage']),
('Is remote work better than working in an office?', 'کیا دور دراز کام دفتر میں کام کرنے سے بہتر ہے؟', 'work_life_balance', 'b2_upper_intermediate', '60-90_seconds', '10_seconds', 'opinion_supporting_arguments_counter_arguments_conclusion', ARRAY['however', 'although', 'on the other hand', 'furthermore', 'nevertheless', 'in contrast', 'additionally'], ARRAY['تاہم', 'اگرچہ', 'دوسری طرف', 'مزید برآں', 'بہر حال', 'اس کے برعکس', 'اس کے علاوہ'], ARRAY['remote', 'office', 'flexibility', 'productivity', 'collaboration', 'work-life balance', 'communication', 'environment'], ARRAY['دور دراز', 'دفتر', 'لچک', 'پیداواری صلاحیت', 'تعاون', 'کام-زندگی توازن', 'مواصلات', 'ماحول'], 'I believe remote work offers significant advantages, but it also has some drawbacks. On the one hand, working from home provides greater flexibility, eliminates commuting time, and often leads to increased productivity. However, it can also create challenges with team collaboration and spontaneous communication. Furthermore, some people struggle with maintaining work-life boundaries when working from home. Nevertheless, I think the ideal solution is a hybrid approach that combines the benefits of both remote and office work, allowing employees to choose what works best for their specific roles and personal preferences.', 'میں سمجھتا ہوں کہ دور دراز کام اہم فوائد فراہم کرتا ہے، لیکن اس کے کچھ نقصانات بھی ہیں۔ ایک طرف، گھر سے کام کرنا زیادہ لچک فراہم کرتا ہے، سفر کا وقت ختم کرتا ہے، اور اکثر بڑھتی ہوئی پیداواری صلاحیت کا باعث بنتا ہے۔ تاہم، یہ ٹیم کے تعاون اور فوری مواصلات کے ساتھ چیلنجز بھی پیدا کر سکتا ہے۔ مزید برآں، کچھ لوگ گھر سے کام کرتے وقت کام-زندگی کی حدود برقرار رکھنے میں جدوجہد کرتے ہیں۔ بہر حال، میں سمجھتا ہوں کہ مثالی حل ایک ہائبرڈ نقطہ نظر ہے جو دور دراز اور دفتری کام دونوں کے فوائد کو ملاتا ہے، ملازمین کو یہ انتخاب کرنے کی اجازت دیتا ہے کہ ان کے مخصوص کرداروں اور ذاتی ترجیحات کے لیے کیا بہترین کام کرتا ہے۔', '{"opinion_clarity": ["clear_position", "balanced_view", "personal_insight"], "connector_usage": ["however", "although", "on_the_other_hand", "furthermore", "nevertheless"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "natural_flow", "minimal_pauses"], "grammar_accuracy": ["complex_sentences", "conditional_structures", "passive_voice", "modals"], "lexical_richness": ["academic_vocabulary", "synonyms", "collocations", "idiomatic_expressions"], "coherence_structure": ["logical_organization", "supporting_arguments", "counter_arguments", "conclusion"], "minimum_score": 80}', ARRAY['Express and defend complex opinions on abstract topics', 'Use transitional phrases and connectors effectively', 'Develop fluency in extended monologue speaking', 'Build confidence in public speaking and structured expression', 'Enhance academic and opinionated vocabulary usage']),
('Should governments invest more in renewable energy?', 'کیا حکومتوں کو قابل تجدید توانائی میں زیادہ سرمایہ کاری کرنی چاہیے؟', 'environment_policy', 'b2_upper_intermediate', '60-90_seconds', '10_seconds', 'opinion_supporting_arguments_counter_arguments_conclusion', ARRAY['however', 'although', 'on the other hand', 'furthermore', 'nevertheless', 'in contrast', 'additionally'], ARRAY['تاہم', 'اگرچہ', 'دوسری طرف', 'مزید برآں', 'بہر حال', 'اس کے برعکس', 'اس کے علاوہ'], ARRAY['renewable', 'energy', 'investment', 'environment', 'sustainability', 'economy', 'technology', 'future'], ARRAY['قابل تجدید', 'توانائی', 'سرمایہ کاری', 'ماحول', 'پائیداری', 'معیشت', 'ٹیکنالوجی', 'مستقبل'], 'I strongly believe that governments should significantly increase their investment in renewable energy. On the one hand, renewable energy sources like solar and wind power are essential for combating climate change and reducing our dependence on fossil fuels. However, some argue that the initial costs are high and the technology is still developing. Furthermore, investing in renewable energy creates new jobs and stimulates economic growth in emerging industries. Nevertheless, I think the long-term benefits far outweigh the short-term costs, and governments have a responsibility to prioritize environmental sustainability for future generations.', 'میں پختہ یقین رکھتا ہوں کہ حکومتوں کو قابل تجدید توانائی میں اپنی سرمایہ کاری میں نمایاں اضافہ کرنا چاہیے۔ ایک طرف، شمسی اور ہوا کی طاقت جیسی قابل تجدید توانائی کے ذرائع موسمیاتی تبدیلی سے نمٹنے اور فوسل فیولز پر ہماری انحصار کو کم کرنے کے لیے ضروری ہیں۔ تاہم، کچھ لوگ دلیل دیتے ہیں کہ ابتدائی اخراجات زیادہ ہیں اور ٹیکنالوجی اب بھی ترقی کر رہی ہے۔ مزید برآں، قابل تجدید توانائی میں سرمایہ کاری نئی ملازمتوں کو پیدا کرتی ہے اور ابھرتی ہوئی صنعتوں میں معاشی ترقی کو تحریک دیتی ہے۔ بہر حال، میں سمجھتا ہوں کہ طویل مدتی فوائد قلیل مدتی اخراجات سے کہیں زیادہ ہیں، اور حکومتوں کا فرض ہے کہ وہ آنے والی نسلوں کے لیے ماحولیاتی پائیداری کو ترجیح دیں۔', '{"opinion_clarity": ["clear_position", "balanced_view", "personal_insight"], "connector_usage": ["however", "although", "on_the_other_hand", "furthermore", "nevertheless"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "natural_flow", "minimal_pauses"], "grammar_accuracy": ["complex_sentences", "conditional_structures", "passive_voice", "modals"], "lexical_richness": ["academic_vocabulary", "synonyms", "collocations", "idiomatic_expressions"], "coherence_structure": ["logical_organization", "supporting_arguments", "counter_arguments", "conclusion"], "minimum_score": 80}', ARRAY['Express and defend complex opinions on abstract topics', 'Use transitional phrases and connectors effectively', 'Develop fluency in extended monologue speaking', 'Build confidence in public speaking and structured expression', 'Enhance academic and opinionated vocabulary usage']),
('Is artificial intelligence a threat or an opportunity?', 'کیا مصنوعی ذہانت ایک خطرہ ہے یا ایک موقع؟', 'technology_future', 'b2_upper_intermediate', '60-90_seconds', '10_seconds', 'opinion_supporting_arguments_counter_arguments_conclusion', ARRAY['however', 'although', 'on the other hand', 'furthermore', 'nevertheless', 'in contrast', 'additionally'], ARRAY['تاہم', 'اگرچہ', 'دوسری طرف', 'مزید برآں', 'بہر حال', 'اس کے برعکس', 'اس کے علاوہ'], ARRAY['artificial intelligence', 'threat', 'opportunity', 'automation', 'jobs', 'innovation', 'ethics', 'regulation'], ARRAY['مصنوعی ذہانت', 'خطرہ', 'موقع', 'خودکار', 'ملازمتوں', 'اختراع', 'اخلاقیات', 'ریگولیشن'], 'I view artificial intelligence as both a significant opportunity and a potential threat that requires careful management. On the one hand, AI has the potential to revolutionize industries, improve healthcare, and solve complex problems that humans cannot tackle alone. However, there are legitimate concerns about job displacement and the need for proper regulation. Furthermore, AI could enhance human capabilities rather than replace them entirely, creating new types of jobs and opportunities. Nevertheless, I believe the key is developing AI responsibly with strong ethical guidelines and ensuring that the benefits are distributed fairly across society.', 'میں مصنوعی ذہانت کو ایک اہم موقع اور ایک ممکنہ خطرہ دونوں کے طور پر دیکھتا ہوں جس کے لیے احتیاطی انتظام کی ضرورت ہے۔ ایک طرف، اے آئی میں صنعتوں کو انقلابی بنانے، صحت کی دیکھ بھال کو بہتر بنانے، اور پیچیدہ مسائل حل کرنے کی صلاحیت ہے جو انسان اکیلے حل نہیں کر سکتے۔ تاہم، ملازمتوں کی جگہ لینے اور مناسب ریگولیشن کی ضرورت کے بارے میں جائز خدشات ہیں۔ مزید برآں، اے آئی انسانوں کی صلاحیتوں کو مکمل طور پر تبدیل کرنے کے بجائے انہیں بڑھا سکتا ہے، نئی قسم کی ملازمتوں اور مواقع پیدا کر سکتا ہے۔ بہر حال، میں سمجھتا ہوں کہ کلید مضبوط اخلاقی رہنما خطوط کے ساتھ ذمہ دارانہ طور پر اے آئی تیار کرنا اور یہ یقینی بنانا ہے کہ فوائد معاشرے میں منصفانہ طور پر تقسیم ہوں۔', '{"opinion_clarity": ["clear_position", "balanced_view", "personal_insight"], "connector_usage": ["however", "although", "on_the_other_hand", "furthermore", "nevertheless"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "natural_flow", "minimal_pauses"], "grammar_accuracy": ["complex_sentences", "conditional_structures", "passive_voice", "modals"], "lexical_richness": ["academic_vocabulary", "synonyms", "collocations", "idiomatic_expressions"], "coherence_structure": ["logical_organization", "supporting_arguments", "counter_arguments", "conclusion"], "minimum_score": 80}', ARRAY['Express and defend complex opinions on abstract topics', 'Use transitional phrases and connectors effectively', 'Develop fluency in extended monologue speaking', 'Build confidence in public speaking and structured expression', 'Enhance academic and opinionated vocabulary usage']);

-- =============================================================================
-- STAGE 4 EXERCISE 2: PROFESSIONAL INTERVIEW SIMULATION
-- =============================================================================

-- Table for Professional Interview Simulation
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage4_exercise2_interview_simulation (
    id SERIAL PRIMARY KEY,
    question TEXT NOT NULL,
    question_urdu TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'B2',
    speaking_duration TEXT NOT NULL,
    thinking_time TEXT NOT NULL,
    expected_structure TEXT NOT NULL,
    expected_keywords TEXT[] NOT NULL,
    expected_keywords_urdu TEXT[] NOT NULL,
    vocabulary_focus TEXT[] NOT NULL,
    vocabulary_focus_urdu TEXT[] NOT NULL,
    model_response TEXT NOT NULL,
    model_response_urdu TEXT NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    learning_objectives TEXT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for Professional Interview Simulation
INSERT INTO public.ai_tutor_stage4_exercise2_interview_simulation (question, question_urdu, category, difficulty, speaking_duration, thinking_time, expected_structure, expected_keywords, expected_keywords_urdu, vocabulary_focus, vocabulary_focus_urdu, model_response, model_response_urdu, evaluation_criteria, learning_objectives) VALUES
('Can you tell me about yourself?', 'کیا آپ اپنے بارے میں بتا سکتے ہیں؟', 'Self-Introduction', 'B2', '60-90 seconds', '15 seconds', 'Background → Skills → Experience → Goals', ARRAY['background', 'skills', 'experience', 'hobbies', 'education', 'career', 'passion', 'goals'], ARRAY['پس منظر', 'مہارتیں', 'تجربہ', 'شوق', 'تعلیم', 'کیریئر', 'جذبہ', 'ہدف'], ARRAY['professional', 'dedicated', 'motivated', 'experienced', 'skilled', 'passionate', 'ambitious', 'reliable'], ARRAY['پیشہ ورانہ', 'مخلص', 'حوصلہ مند', 'تجربہ کار', 'ہنر مند', 'جذبہ مند', 'بلند حوصلہ', 'قابل اعتماد'], 'I''m a dedicated professional with over five years of experience in software development. I''m passionate about creating innovative solutions and have strong skills in problem-solving and team collaboration. In my free time, I enjoy learning new technologies and contributing to open-source projects. I''m ambitious about advancing my career and making meaningful contributions to the industry.', 'میں پانچ سال سے زیادہ کے تجربے کے ساتھ سافٹ ویئر ڈویلپمنٹ میں ایک مخلص پیشہ ور ہوں۔ میں اختراعی حل بنانے کا شوق رکھتا ہوں اور مسئلہ حل کرنے اور ٹیم کے ساتھ کام کرنے میں مضبوط مہارتیں رکھتا ہوں۔ اپنے فارغ وقت میں، میں نئی ٹیکنالوجیز سیکھنے اور اوپن سورس پروجیکٹس میں حصہ لینے سے لطف اندوز ہوتا ہوں۔ میں اپنے کیریئر کو آگے بڑھانے اور صنعت میں معنی خیز شراکت کرنے کے لیے بلند حوصلہ ہوں۔', '{"answer_relevance": 25, "confidence_tone": 20, "grammar_fluency": 25, "interview_vocabulary": 30}', ARRAY['Build professional self-introduction skills', 'Use formal interview vocabulary', 'Demonstrate confidence in tone', 'Organize thoughts under pressure']),
('Why do you want this job?', 'آپ کو یہ نوکری کیوں چاہیے؟', 'Motivation', 'B2', '60-90 seconds', '15 seconds', 'Interest → Skills Match → Company Values → Career Goals', ARRAY['interest', 'passion', 'skills', 'fit', 'opportunity', 'growth', 'challenge', 'values'], ARRAY['دلچسپی', 'جذبہ', 'مہارتیں', 'موافقت', 'موقع', 'ترقی', 'چیلنج', 'اقدار'], ARRAY['excited', 'enthusiastic', 'perfect fit', 'aligned', 'opportunity', 'growth potential', 'challenging', 'innovative'], ARRAY['پرجوش', 'جذبہ مند', 'مکمل موافقت', 'ہم آہنگ', 'موقع', 'ترقی کی صلاحیت', 'چیلنجنگ', 'اختراعی'], 'I''m genuinely excited about this opportunity because it perfectly aligns with my career goals and skills. I''m passionate about innovation and this role offers the chance to work on cutting-edge projects. The company''s values of collaboration and excellence resonate with my professional philosophy. I see tremendous growth potential here and I''m enthusiastic about contributing to the team''s success while developing my own expertise.', 'میں اس موقع کے بارے میں واقعی پرجوش ہوں کیونکہ یہ میرے کیریئر کے اہداف اور مہارتوں کے ساتھ مکمل طور پر ہم آہنگ ہے۔ میں اختراع کا شوق رکھتا ہوں اور یہ کردار جدید ترین پروجیکٹس پر کام کرنے کا موقع فراہم کرتا ہے۔ کمپنی کی تعاون اور فضیلت کی اقدار میرے پیشہ ورانہ فلسفے کے ساتھ ہم آہنگ ہیں۔ میں یہاں بہت زیادہ ترقی کی صلاحیت دیکھتا ہوں اور میں ٹیم کی کامیابی میں حصہ لینے اور اپنی مہارت کو فروغ دینے کے بارے میں جذبہ مند ہوں۔', '{"answer_relevance": 30, "confidence_tone": 20, "grammar_fluency": 25, "interview_vocabulary": 25}', ARRAY['Express genuine interest in the role', 'Connect personal goals with company mission', 'Demonstrate research about the company', 'Show enthusiasm and motivation']),
('What are your greatest strengths?', 'آپ کی سب سے بڑی طاقتیں کیا ہیں؟', 'Strengths', 'B2', '60-90 seconds', '15 seconds', 'Strength → Example → Impact → Relevance', ARRAY['strengths', 'skills', 'abilities', 'experience', 'achievements', 'examples', 'impact', 'relevance'], ARRAY['طاقتیں', 'مہارتیں', 'صلاحیتیں', 'تجربہ', 'کامیابیاں', 'مثالیں', 'اثر', 'مناسبت'], ARRAY['analytical', 'leadership', 'communication', 'problem-solving', 'adaptability', 'creativity', 'teamwork', 'initiative'], ARRAY['تجزیاتی', 'قیادت', 'مواصلات', 'مسئلہ حل', 'موافقت', 'تخلیقی صلاحیت', 'ٹیم ورک', 'پہل'], 'My greatest strengths are my analytical thinking and leadership abilities. I have strong problem-solving skills that help me break down complex challenges into manageable tasks. For example, in my previous role, I led a team of five developers to deliver a project two weeks ahead of schedule by implementing efficient project management strategies. I''m also highly adaptable and enjoy learning new technologies quickly. These strengths make me well-suited for dynamic environments where innovation and collaboration are valued.', 'میری سب سے بڑی طاقتیں میری تجزیاتی سوچ اور قیادت کی صلاحیتیں ہیں۔ میرے پاس مضبوط مسئلہ حل کرنے کی مہارتیں ہیں جو مجھے پیچیدہ چیلنجز کو قابل انتظام کاموں میں تقسیم کرنے میں مدد کرتی ہیں۔ مثال کے طور پر، اپنے پچھلے کردار میں، میں نے پانچ ڈویلپرز کی ٹیم کی قیادت کی اور موثر پروجیکٹ مینجمنٹ کی حکمت عملیوں کو نافذ کرکے ایک پروجیکٹ کو شیڈول سے دو ہفتے پہلے مکمل کیا۔ میں بھی بہت موافقت پذیر ہوں اور نئی ٹیکنالوجیز کو جلدی سیکھنے سے لطف اندوز ہوتا ہوں۔ یہ طاقتیں مجھے متحرک ماحول کے لیے موزوں بناتی ہیں جہاں اختراع اور تعاون کو قدر کی نگاہ سے دیکھا جاتا ہے۔', '{"answer_relevance": 25, "confidence_tone": 20, "grammar_fluency": 25, "interview_vocabulary": 30}', ARRAY['Identify and articulate key strengths', 'Provide specific examples with impact', 'Connect strengths to job requirements', 'Demonstrate self-awareness and confidence']),
('What is your biggest weakness?', 'آپ کی سب سے بڑی کمزوری کیا ہے؟', 'Weaknesses', 'B2', '60-90 seconds', '15 seconds', 'Weakness → Improvement → Learning → Growth', ARRAY['weakness', 'challenge', 'improvement', 'learning', 'growth', 'development', 'effort', 'progress'], ARRAY['کمزوری', 'چیلنج', 'بہتری', 'سیکھنا', 'ترقی', 'ترقی', 'کوشش', 'ترقی'], ARRAY['perfectionist', 'delegation', 'public speaking', 'time management', 'patience', 'confidence', 'technical', 'communication'], ARRAY['کمال پسند', 'تفویض', 'عوامی تقریر', 'وقت کا انتظام', 'صبر', 'اعتماد', 'تکنیکی', 'مواصلات'], 'I used to struggle with delegation because I wanted to ensure everything was done perfectly. However, I''ve learned that this approach can limit team growth and create bottlenecks. I''ve been actively working on this by trusting my team members more and focusing on clear communication of expectations. I''ve taken a project management course and now use tools to track progress effectively. This experience has taught me that delegation actually improves overall team performance and allows me to focus on strategic priorities.', 'میں تفویض کے ساتھ جدوجہد کرتا تھا کیونکہ میں یقینی بنانا چاہتا تھا کہ ہر چیز کامل طور پر ہو۔ تاہم، میں نے سیکھا ہے کہ یہ نقطہ نظر ٹیم کی ترقی کو محدود کر سکتا ہے اور رکاوٹیں پیدا کر سکتا ہے۔ میں اس پر فعال طور پر کام کر رہا ہوں اپنے ٹیم ممبران پر زیادہ اعتماد کرکے اور توقعات کی واضح مواصلات پر توجہ مرکوز کرکے۔ میں نے ایک پروجیکٹ مینجمنٹ کورس لیا ہے اور اب ترقی کو مؤثر طریقے سے ٹریک کرنے کے لیے اوزار استعمال کرتا ہوں۔ اس تجربے نے مجھے سکھایا ہے کہ تفویض دراصل مجموعی ٹیم کی کارکردگی کو بہتر بناتی ہے اور مجھے حکمت عملی کی ترجیحات پر توجہ مرکوز کرنے کی اجازت دیتی ہے۔', '{"answer_relevance": 25, "confidence_tone": 20, "grammar_fluency": 25, "interview_vocabulary": 30}', ARRAY['Turn weaknesses into growth opportunities', 'Show self-awareness and improvement mindset', 'Demonstrate learning and development', 'Maintain positive and professional tone']),
('Where do you see yourself in five years?', 'آپ اپنے آپ کو پانچ سال میں کہاں دیکھتے ہیں؟', 'Career Goals', 'B2', '60-90 seconds', '15 seconds', 'Short-term → Long-term → Skills → Contribution', ARRAY['future', 'career', 'goals', 'aspirations', 'growth', 'development', 'leadership', 'contribution'], ARRAY['مستقبل', 'کیریئر', 'اہداف', 'آرزوئیں', 'ترقی', 'ترقی', 'قیادت', 'شراکت'], ARRAY['ambitious', 'vision', 'leadership', 'expertise', 'mentoring', 'innovation', 'impact', 'advancement'], ARRAY['بلند حوصلہ', 'نقطہ نظر', 'قیادت', 'مہارت', 'رہنمائی', 'اختراع', 'اثر', 'ترقی'], 'In five years, I see myself in a senior leadership role where I can mentor junior developers and drive technical innovation. I''m ambitious about developing expertise in emerging technologies like AI and machine learning. I envision leading cross-functional teams to deliver impactful projects that solve real-world problems. I''m also passionate about contributing to the tech community through speaking engagements and open-source contributions. Ultimately, I want to be known as someone who not only delivers excellent technical solutions but also helps others grow and succeed in their careers.', 'پانچ سال میں، میں اپنے آپ کو ایک سینئر قیادت کے کردار میں دیکھتا ہوں جہاں میں جونیئر ڈویلپرز کی رہنمائی کر سکتا ہوں اور تکنیکی اختراع کو آگے بڑھا سکتا ہوں۔ میں اے آئی اور مشین لرننگ جیسی ابھرتی ہوئی ٹیکنالوجیز میں مہارت حاصل کرنے کے بارے میں بلند حوصلہ ہوں۔ میں کراس فنکشنل ٹیموں کی قیادت کرنے کا تصور کرتا ہوں تاکہ حقیقی دنیا کے مسائل حل کرنے والے مؤثر پروجیکٹس فراہم کر سکیں۔ میں بھی تقریری مشغولیات اور اوپن سورس شراکت کے ذریعے ٹیک کمیونٹی میں حصہ ڈالنے کا شوق رکھتا ہوں۔ بالآخر، میں جانا جانا چاہتا ہوں کہ میں نہ صرف بہترین تکنیکی حل فراہم کرتا ہوں بلکہ دوسروں کو ان کے کیریئر میں ترقی اور کامیابی میں بھی مدد کرتا ہوں۔', '{"answer_relevance": 30, "confidence_tone": 20, "grammar_fluency": 25, "interview_vocabulary": 25}', ARRAY['Demonstrate long-term career planning', 'Show ambition and vision', 'Connect personal goals with company growth', 'Express commitment to professional development']);

-- =============================================================================
-- STAGE 4 EXERCISE 3: NEWS SUMMARIZATION & ANALYSIS
-- =============================================================================

-- Table for News Summarization & Analysis
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage4_exercise3_news_summarization (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    title_urdu TEXT NOT NULL,
    summary_text TEXT NOT NULL,
    summary_text_urdu TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'B2',
    listening_duration TEXT NOT NULL,
    summary_time TEXT NOT NULL,
    expected_structure TEXT NOT NULL,
    expected_keywords TEXT[] NOT NULL,
    expected_keywords_urdu TEXT[] NOT NULL,
    vocabulary_focus TEXT[] NOT NULL,
    vocabulary_focus_urdu TEXT[] NOT NULL,
    model_summary TEXT NOT NULL,
    model_summary_urdu TEXT NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    learning_objectives TEXT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for News Summarization & Analysis
INSERT INTO public.ai_tutor_stage4_exercise3_news_summarization (title, title_urdu, summary_text, summary_text_urdu, category, difficulty, listening_duration, summary_time, expected_structure, expected_keywords, expected_keywords_urdu, vocabulary_focus, vocabulary_focus_urdu, model_summary, model_summary_urdu, evaluation_criteria, learning_objectives) VALUES
('Global Climate Summit Reaches Historic Agreement', 'عالمی آب و ہوا سربراہی اجلاس میں تاریخی معاہدہ', 'World leaders at the COP28 climate summit have reached a historic agreement to phase out fossil fuels by 2050. The landmark deal includes commitments from 195 countries to reduce greenhouse gas emissions by 50% by 2030. Developing nations will receive $100 billion annually in climate finance. Environmental experts call this the most significant climate agreement in history.', 'COP28 آب و ہوا سربراہی اجلاس میں عالمی رہنماؤں نے 2050 تک فوسل فیولز کو ختم کرنے کا تاریخی معاہدہ کیا ہے۔ اس اہم معاہدے میں 195 ممالک نے 2030 تک گرین ہاؤس گیسوں کے اخراج کو 50% کم کرنے کا عہد کیا ہے۔ ترقی پذیر ممالک کو سالانہ 100 ارب ڈالر کی آب و ہوا کی مالی امداد ملے گی۔ ماحولیاتی ماہرین اسے تاریخ کا سب سے اہم آب و ہوا معاہدہ قرار دے رہے ہیں۔', 'Environment & Climate', 'B2', '45-60 seconds', '30-45 seconds', 'Main Event → Key Details → Impact → Future Implications', ARRAY['climate summit', 'agreement', 'fossil fuels', 'emissions', 'finance', 'countries', 'commitments', 'environmental'], ARRAY['آب و ہوا سربراہی اجلاس', 'معاہدہ', 'فوسل فیولز', 'اخراج', 'مالی امداد', 'ممالک', 'عہد', 'ماحولیاتی'], ARRAY['landmark', 'phase out', 'greenhouse gas', 'commitments', 'climate finance', 'developing nations', 'environmental experts', 'significant'], ARRAY['اہم', 'ختم کرنا', 'گرین ہاؤس گیس', 'عہد', 'آب و ہوا کی مالی امداد', 'ترقی پذیر ممالک', 'ماحولیاتی ماہرین', 'اہم'], 'The COP28 climate summit resulted in a historic agreement where 195 countries committed to phasing out fossil fuels by 2050 and reducing emissions by 50% by 2030. The deal includes $100 billion in annual climate finance for developing nations. This represents the most significant climate agreement in history.', 'COP28 آب و ہوا سربراہی اجلاس میں 195 ممالک نے 2050 تک فوسل فیولز کو ختم کرنے اور 2030 تک اخراج کو 50% کم کرنے کا تاریخی معاہدہ کیا۔ معاہدے میں ترقی پذیر ممالک کے لیے سالانہ 100 ارب ڈالر کی آب و ہوا کی مالی امداد شامل ہے۔ یہ تاریخ کا سب سے اہم آب و ہوا معاہدہ ہے۔', '{"main_points_coverage": 30, "grammar_structure": 25, "paraphrasing_skills": 25, "neutral_tone": 20}', ARRAY['Summarize complex international agreements', 'Use formal vocabulary for environmental topics', 'Demonstrate understanding of global issues', 'Practice neutral reporting tone']),
('Tech Giant Launches Revolutionary AI Assistant', 'ٹیک جائنٹ نے انقلابی اے آئی اسسٹنٹ لانچ کیا', 'A major technology company has unveiled its latest artificial intelligence assistant, capable of understanding context and generating human-like responses. The AI system can process multiple languages, assist with complex problem-solving, and integrate with various applications. Industry experts predict this could revolutionize how people interact with technology. The company plans to make it available to consumers within six months.', 'ایک بڑی ٹیکنالوجی کمپنی نے اپنا تازہ ترین مصنوعی ذہانت کا اسسٹنٹ متعارف کرایا ہے، جو سیاق و سباق کو سمجھنے اور انسانی جیسے جوابات تیار کرنے کی صلاحیت رکھتا ہے۔ اے آئی سسٹم متعدد زبانوں کو پروسیس کر سکتا ہے، پیچیدہ مسئلہ حل کرنے میں مدد کر سکتا ہے، اور مختلف ایپلیکیشنز کے ساتھ مربوط ہو سکتا ہے۔ صنعت کے ماہرین پیش گوئی کرتے ہیں کہ یہ ٹیکنالوجی کے ساتھ لوگوں کے تعامل کے طریقے کو انقلابی بنا سکتا ہے۔ کمپنی اسے چھ ماہ کے اندر صارفین کو دستیاب کرانے کا منصوبہ رکھتی ہے۔', 'Technology & Innovation', 'B2', '40-55 seconds', '25-35 seconds', 'Product Launch → Capabilities → Impact → Availability', ARRAY['technology', 'AI assistant', 'artificial intelligence', 'languages', 'problem-solving', 'revolutionize', 'applications', 'consumers'], ARRAY['ٹیکنالوجی', 'اے آئی اسسٹنٹ', 'مصنوعی ذہانت', 'زبانیں', 'مسئلہ حل', 'انقلابی', 'ایپلیکیشنز', 'صارفین'], ARRAY['unveiled', 'capable', 'context', 'integrate', 'revolutionize', 'interact', 'artificial intelligence', 'complex'], ARRAY['متعارف کرایا', 'قابل', 'سیاق و سباق', 'مربوط', 'انقلابی', 'تعامل', 'مصنوعی ذہانت', 'پیچیدہ'], 'A major tech company has launched a new AI assistant that can understand context and generate human-like responses. The system processes multiple languages and helps with complex problem-solving. Experts believe this could revolutionize human-technology interaction, with consumer availability expected within six months.', 'ایک بڑی ٹیک کمپنی نے نیا اے آئی اسسٹنٹ لانچ کیا ہے جو سیاق و سباق کو سمجھ سکتا ہے اور انسانی جیسے جوابات تیار کر سکتا ہے۔ سسٹم متعدد زبانوں کو پروسیس کرتا ہے اور پیچیدہ مسئلہ حل کرنے میں مدد کرتا ہے۔ ماہرین کا خیال ہے کہ یہ انسانی-ٹیکنالوجی تعامل کو انقلابی بنا سکتا ہے، جس کی صارفین کو دستیابی چھ ماہ کے اندر متوقع ہے۔', '{"main_points_coverage": 30, "grammar_structure": 25, "paraphrasing_skills": 25, "neutral_tone": 20}', ARRAY['Summarize technological innovations', 'Use technical vocabulary accurately', 'Demonstrate understanding of AI developments', 'Practice concise reporting style']),
('Economic Recovery Shows Strong Growth Indicators', 'معاشی بحالی مضبوط ترقی کے اشارے دکھاتی ہے', 'The latest economic data reveals robust growth indicators across multiple sectors, with manufacturing output increasing by 8% and unemployment rates dropping to their lowest levels in five years. Consumer spending has risen significantly, particularly in technology and healthcare sectors. Central banks are cautiously optimistic about sustained economic recovery, though inflation concerns remain. The positive trends suggest a resilient economy adapting to post-pandemic challenges.', 'تازہ ترین معاشی ڈیٹا متعدد شعبوں میں مضبوط ترقی کے اشارے ظاہر کرتا ہے، جس میں مینوفیکچرنگ کی پیداوار 8% بڑھ گئی ہے اور بے روزگاری کی شرح پانچ سال کے کم ترین سطح پر آ گئی ہے۔ صارفین کی خرچ میں خاص طور پر ٹیکنالوجی اور صحت کی دیکھ بھال کے شعبوں میں نمایاں اضافہ ہوا ہے۔ مرکزی بینک مستقل معاشی بحالی کے بارے میں احتیاط سے پرامید ہیں، حالانکہ افراط زر کے خدشات برقرار ہیں۔ مثبت رجحانات ایک لچکدار معیشت کی نشاندہی کرتے ہیں جو وبائی امراض کے بعد کے چیلنجز کے ساتھ مطابقت پیدا کر رہی ہے۔', 'Economy & Finance', 'B2', '50-65 seconds', '35-45 seconds', 'Economic Data → Sector Performance → Consumer Trends → Outlook', ARRAY['economic', 'growth', 'manufacturing', 'unemployment', 'consumer', 'spending', 'recovery', 'inflation'], ARRAY['معاشی', 'ترقی', 'مینوفیکچرنگ', 'بے روزگاری', 'صارف', 'خرچ', 'بحالی', 'افراط زر'], ARRAY['robust', 'output', 'significantly', 'cautiously', 'optimistic', 'sustained', 'resilient', 'adapting'], ARRAY['مضبوط', 'پیداوار', 'نمایاں طور پر', 'احتیاط سے', 'پرامید', 'مستقل', 'لچکدار', 'مطابقت'], 'Economic data shows strong growth with manufacturing up 8% and unemployment at five-year lows. Consumer spending has increased significantly, especially in technology and healthcare. Central banks are cautiously optimistic about sustained recovery, though inflation concerns persist. The trends indicate a resilient economy adapting to post-pandemic challenges.', 'معاشی ڈیٹا مضبوط ترقی دکھاتا ہے جس میں مینوفیکچرنگ 8% بڑھ گئی اور بے روزگاری پانچ سال کی کم ترین سطح پر ہے۔ صارفین کی خرچ میں نمایاں اضافہ ہوا ہے، خاص طور پر ٹیکنالوجی اور صحت کی دیکھ بھال میں۔ مرکزی بینک مستقل بحالی کے بارے میں احتیاط سے پرامید ہیں، حالانکہ افراط زر کے خدشات برقرار ہیں۔ رجحانات ایک لچکدار معیشت کی نشاندہی کرتے ہیں جو وبائی امراض کے بعد کے چیلنجز کے ساتھ مطابقت پیدا کر رہی ہے۔', '{"main_points_coverage": 30, "grammar_structure": 25, "paraphrasing_skills": 25, "neutral_tone": 20}', ARRAY['Summarize economic data and trends', 'Use financial vocabulary appropriately', 'Demonstrate understanding of economic indicators', 'Practice objective reporting style']),
('Space Mission Achieves Historic Mars Landing', 'خلائی مشن نے تاریخی مریخ لینڈنگ حاصل کی', 'A multinational space mission has successfully landed a rover on Mars, marking the first time a vehicle has touched down on the planet''s surface in over a decade. The mission aims to search for signs of ancient microbial life and study the planet''s geology. The rover is equipped with advanced scientific instruments and will conduct experiments for the next two years. This achievement represents a significant milestone in space exploration and international cooperation.', 'ایک کثیر قومی خلائی مشن نے کامیابی سے مریخ پر ایک روور اتارا ہے، جو ایک دہائی سے زیادہ عرصے میں پہلی بار کسی گاڑی کے سیارے کی سطح کو چھونے کی نشاندہی کرتا ہے۔ مشن کا مقصد قدیم مائکروبیل زندگی کے نشانات تلاش کرنا اور سیارے کی ارضیات کا مطالعہ کرنا ہے۔ روور جدید سائنسی آلات سے لیس ہے اور اگلے دو سال تک تجربات کرے گا۔ یہ کامیابی خلائی تحقیق اور بین الاقوامی تعاون میں ایک اہم سنگ میل کی نمائندگی کرتی ہے۔', 'Science & Space', 'B2', '45-60 seconds', '30-40 seconds', 'Mission Achievement → Objectives → Equipment → Significance', ARRAY['space', 'mission', 'Mars', 'rover', 'landing', 'microbial', 'life', 'geology'], ARRAY['خلائی', 'مشن', 'مریخ', 'روور', 'لینڈنگ', 'مائکروبیل', 'زندگی', 'ارضیات'], ARRAY['multinational', 'successfully', 'touched down', 'ancient', 'equipped', 'instruments', 'milestone', 'cooperation'], ARRAY['کثیر قومی', 'کامیابی سے', 'چھوا', 'قدیم', 'لیس', 'آلات', 'سنگ میل', 'تعاون'], 'A multinational space mission successfully landed a rover on Mars for the first time in over a decade. The mission will search for ancient microbial life and study Mars geology. The rover has advanced scientific instruments and will conduct two years of experiments. This achievement marks a significant milestone in space exploration and international cooperation.', 'ایک کثیر قومی خلائی مشن نے ایک دہائی سے زیادہ عرصے میں پہلی بار کامیابی سے مریخ پر روور اتارا۔ مشن قدیم مائکروبیل زندگی تلاش کرے گا اور مریخ کی ارضیات کا مطالعہ کرے گا۔ روور کے پاس جدید سائنسی آلات ہیں اور دو سال تک تجربات کرے گا۔ یہ کامیابی خلائی تحقیق اور بین الاقوامی تعاون میں ایک اہم سنگ میل کی نشاندہی کرتی ہے۔', '{"main_points_coverage": 30, "grammar_structure": 25, "paraphrasing_skills": 25, "neutral_tone": 20}', ARRAY['Summarize scientific achievements', 'Use space exploration vocabulary', 'Demonstrate understanding of scientific missions', 'Practice technical reporting style']),
('Global Health Initiative Targets Disease Prevention', 'عالمی صحت کی پہل بیماری کی روک تھام کو نشانہ بناتی ہے', 'A new global health initiative has been launched to combat preventable diseases through improved vaccination programs and public health education. The program targets regions with limited healthcare access and aims to reduce child mortality rates by 40% within five years. International organizations are collaborating to provide funding, medical supplies, and training for healthcare workers. The initiative represents a coordinated effort to address health disparities and strengthen healthcare systems worldwide.', 'بہتر ویکسینیشن پروگرامز اور عوامی صحت کی تعلیم کے ذریعے قابل روک تھام بیماریوں سے نمٹنے کے لیے ایک نئی عالمی صحت کی پہل شروع کی گئی ہے۔ پروگرام محدود صحت کی دیکھ بھال تک رسائی والے علاقوں کو نشانہ بناتا ہے اور پانچ سال کے اندر بچوں کی اموات کی شرح کو 40% کم کرنے کا ہدف رکھتا ہے۔ بین الاقوامی تنظیمیں صحت کی دیکھ بھال کے کارکنوں کے لیے فنڈنگ، طبی سامان، اور تربیت فراہم کرنے کے لیے تعاون کر رہی ہیں۔ یہ پہل صحت کی عدم مساوات کو حل کرنے اور دنیا بھر میں صحت کی دیکھ بھال کے نظاموں کو مضبوط بنانے کے لیے ایک مربوط کوشش کی نمائندگی کرتی ہے۔', 'Health & Medicine', 'B2', '50-65 seconds', '35-45 seconds', 'Initiative Launch → Targets → Methods → Global Impact', ARRAY['health', 'initiative', 'diseases', 'vaccination', 'prevention', 'mortality', 'healthcare', 'workers'], ARRAY['صحت', 'پہل', 'بیماریاں', 'ویکسینیشن', 'روک تھام', 'اموات', 'صحت کی دیکھ بھال', 'کارکن'], ARRAY['combat', 'preventable', 'improved', 'targets', 'collaborating', 'funding', 'disparities', 'strengthen'], ARRAY['نمٹنا', 'قابل روک تھام', 'بہتر', 'نشانہ', 'تعاون', 'فنڈنگ', 'عدم مساوات', 'مضبوط'], 'A new global health initiative aims to combat preventable diseases through improved vaccination and public health education. The program targets regions with limited healthcare access and seeks to reduce child mortality by 40% in five years. International organizations are collaborating to provide funding, supplies, and training. This represents a coordinated effort to address health disparities and strengthen global healthcare systems.', 'ایک نئی عالمی صحت کی پہل بہتر ویکسینیشن اور عوامی صحت کی تعلیم کے ذریعے قابل روک تھام بیماریوں سے نمٹنے کا ہدف رکھتی ہے۔ پروگرام محدود صحت کی دیکھ بھال تک رسائی والے علاقوں کو نشانہ بناتا ہے اور پانچ سال میں بچوں کی اموات کو 40% کم کرنے کی کوشش کرتا ہے۔ بین الاقوامی تنظیمیں فنڈنگ، سامان، اور تربیت فراہم کرنے کے لیے تعاون کر رہی ہیں۔ یہ صحت کی عدم مساوات کو حل کرنے اور عالمی صحت کی دیکھ بھال کے نظاموں کو مضبوط بنانے کے لیے ایک مربوط کوشش کی نمائندگی کرتا ہے۔', '{"main_points_coverage": 30, "grammar_structure": 25, "paraphrasing_skills": 25, "neutral_tone": 20}', ARRAY['Summarize global health initiatives', 'Use medical and public health vocabulary', 'Demonstrate understanding of healthcare systems', 'Practice objective health reporting']);

-- =============================================================================
-- INDEXES FOR PERFORMANCE
-- =============================================================================

-- Indexes for Opinion Expression & Debate
CREATE INDEX IF NOT EXISTS idx_opinion_debate_category ON public.ai_tutor_stage4_exercise1_opinion_debate(category);
CREATE INDEX IF NOT EXISTS idx_opinion_debate_difficulty ON public.ai_tutor_stage4_exercise1_opinion_debate(difficulty);
CREATE INDEX IF NOT EXISTS idx_opinion_debate_topic ON public.ai_tutor_stage4_exercise1_opinion_debate(topic);

-- Indexes for Professional Interview Simulation
CREATE INDEX IF NOT EXISTS idx_interview_simulation_category ON public.ai_tutor_stage4_exercise2_interview_simulation(category);
CREATE INDEX IF NOT EXISTS idx_interview_simulation_difficulty ON public.ai_tutor_stage4_exercise2_interview_simulation(difficulty);
CREATE INDEX IF NOT EXISTS idx_interview_simulation_question ON public.ai_tutor_stage4_exercise2_interview_simulation(question);

-- Indexes for News Summarization & Analysis
CREATE INDEX IF NOT EXISTS idx_news_summarization_category ON public.ai_tutor_stage4_exercise3_news_summarization(category);
CREATE INDEX IF NOT EXISTS idx_news_summarization_difficulty ON public.ai_tutor_stage4_exercise3_news_summarization(difficulty);
CREATE INDEX IF NOT EXISTS idx_news_summarization_title ON public.ai_tutor_stage4_exercise3_news_summarization(title);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE public.ai_tutor_stage4_exercise1_opinion_debate ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_tutor_stage4_exercise2_interview_simulation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_tutor_stage4_exercise3_news_summarization ENABLE ROW LEVEL SECURITY;

-- RLS Policies for public access (these are content tables, not user-specific)
CREATE POLICY "Anyone can view opinion debate topics" ON public.ai_tutor_stage4_exercise1_opinion_debate FOR SELECT USING (true);
CREATE POLICY "Anyone can view interview simulation questions" ON public.ai_tutor_stage4_exercise2_interview_simulation FOR SELECT USING (true);
CREATE POLICY "Anyone can view news summarization content" ON public.ai_tutor_stage4_exercise3_news_summarization FOR SELECT USING (true);

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

-- Grant permissions for all tables
GRANT ALL ON public.ai_tutor_stage4_exercise1_opinion_debate TO anon, authenticated;
GRANT ALL ON public.ai_tutor_stage4_exercise2_interview_simulation TO anon, authenticated;
GRANT ALL ON public.ai_tutor_stage4_exercise3_news_summarization TO anon, authenticated;

-- Grant permissions for sequences
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Verify data insertion
SELECT 'Opinion Expression & Debate' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage4_exercise1_opinion_debate
UNION ALL
SELECT 'Professional Interview Simulation' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage4_exercise2_interview_simulation
UNION ALL
SELECT 'News Summarization & Analysis' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage4_exercise3_news_summarization;

-- Sample data verification
SELECT 'Sample Opinion Expression & Debate:' as info;
SELECT id, topic, topic_urdu, category FROM public.ai_tutor_stage4_exercise1_opinion_debate LIMIT 3;

SELECT 'Sample Professional Interview Simulation:' as info;
SELECT id, question, question_urdu, category FROM public.ai_tutor_stage4_exercise2_interview_simulation LIMIT 3;

SELECT 'Sample News Summarization & Analysis:' as info;
SELECT id, title, title_urdu, category FROM public.ai_tutor_stage4_exercise3_news_summarization LIMIT 3;
