-- =============================================================================
-- AI English Tutor - Stage 3 Exercises Database Schema
-- =============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- STAGE 3 EXERCISE 1: STORYTELLING NARRATION
-- =============================================================================

-- Table for Storytelling Narration
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage3_exercise1_storytelling (
    id SERIAL PRIMARY KEY,
    prompt TEXT NOT NULL,
    prompt_urdu TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'b1_intermediate',
    tense_focus TEXT NOT NULL,
    expected_structure TEXT NOT NULL,
    example_keywords TEXT[] NOT NULL,
    example_keywords_urdu TEXT[] NOT NULL,
    model_answer TEXT NOT NULL,
    model_answer_urdu TEXT NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    learning_objectives TEXT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for Storytelling Narration
INSERT INTO public.ai_tutor_stage3_exercise1_storytelling (prompt, prompt_urdu, category, difficulty, tense_focus, expected_structure, example_keywords, example_keywords_urdu, model_answer, model_answer_urdu, evaluation_criteria, learning_objectives) VALUES
('Tell me about a time you felt really happy.', 'مجھے ایک ایسے وقت کے بارے میں بتائیں جب آپ واقعی خوش تھے۔', 'emotional_experiences', 'b1_intermediate', 'past_simple', 'beginning_middle_end', ARRAY['was', 'were', 'felt', 'happy', 'because', 'when', 'then', 'finally'], ARRAY['تھا', 'تھے', 'محسوس', 'خوش', 'کیونکہ', 'جب', 'پھر', 'آخر میں'], 'I was really happy when I got my first job. I had been looking for work for months, and when I finally got the call, I felt excited and relieved. Then I celebrated with my family, and finally I started working the next week.', 'میں واقعی خوش تھا جب مجھے اپنی پہلی نوکری ملی۔ میں مہینوں سے کام تلاش کر رہا تھا، اور جب آخر میں مجھے کال آئی، تو میں پرجوش اور مطمئن محسوس کر رہا تھا۔ پھر میں نے اپنے خاندان کے ساتھ جشن منایا، اور آخر میں میں نے اگلے ہفتے کام شروع کر دیا۔', '{"past_tense_usage": ["was", "were", "had", "got", "felt", "started"], "narrative_structure": ["when", "then", "finally", "because"], "descriptive_language": ["really", "excited", "relieved", "celebrated"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice past tense verbs and time-based storytelling', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Describe a fun day you had recently.', 'ایک تفریحی دن کی تفصیل بتائیں جو آپ نے حال ہی میں گزارا۔', 'recent_experiences', 'b1_intermediate', 'past_simple', 'beginning_middle_end', ARRAY['went', 'with friends', 'park', 'games', 'fun', 'enjoyed', 'played', 'ate'], ARRAY['گئے', 'دوستوں کے ساتھ', 'پارک', 'کھیل', 'تفریح', 'لطف', 'کھیلا', 'کھایا'], 'I went to the park with my friends last weekend. We played cricket and had a picnic under the trees. Then we walked around the lake and took some photos. Finally, we ate ice cream and went home feeling very happy.', 'میں پچھلے ہفتے اپنے دوستوں کے ساتھ پارک گیا۔ ہم نے کرکٹ کھیلی اور درختوں کے نیچے پکنک کی۔ پھر ہم جھیل کے ارد گرد گھومے اور کچھ تصاویر لیں۔ آخر میں، ہم نے آئس کریم کھائی اور بہت خوش محسوس کرتے ہوئے گھر گئے۔', '{"past_tense_usage": ["went", "played", "had", "walked", "took", "ate", "felt"], "narrative_structure": ["last weekend", "then", "finally", "under", "around"], "descriptive_language": ["fun", "picnic", "trees", "lake", "photos", "happy"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice past tense verbs and time-based storytelling', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Tell me about a challenge you overcame.', 'مجھے ایک چیلنج کے بارے میں بتائیں جسے آپ نے عبور کیا۔', 'personal_growth', 'b1_intermediate', 'past_simple', 'problem_solution_outcome', ARRAY['challenge', 'difficult', 'problem', 'solved', 'overcame', 'learned', 'improved'], ARRAY['چیلنج', 'مشکل', 'مسئلہ', 'حل', 'عبور', 'سیکھا', 'بہتر'], 'I had a challenge learning to drive. At first, I was very nervous and made many mistakes. The problem was that I was afraid of traffic. I solved this by practicing more and taking extra lessons. I overcame my fear and learned to drive confidently. Now I feel much more independent.', 'مجھے گاڑی چلانا سیکھنے میں چیلنج تھا۔ پہلے میں بہت گھبرا جاتا تھا اور بہت سی غلطیاں کرتا تھا۔ مسئلہ یہ تھا کہ مجھے ٹریفک سے ڈر لگتا تھا۔ میں نے اسے زیادہ مشق کرنے اور اضافی سبق لینے سے حل کیا۔ میں نے اپنے خوف پر قابو پایا اور اعتماد کے ساتھ گاڑی چلانا سیکھا۔ اب میں خود کو زیادہ آزاد محسوس کرتا ہوں۔', '{"past_tense_usage": ["had", "was", "made", "solved", "overcame", "learned", "feel"], "narrative_structure": ["at first", "the problem was", "I solved this by", "now"], "descriptive_language": ["nervous", "afraid", "confidently", "independent"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice past tense verbs and time-based storytelling', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Describe your favorite childhood memory.', 'اپنے پسندیدہ بچپن کے یاد کے بارے میں بتائیں۔', 'childhood_memories', 'b1_intermediate', 'past_simple', 'beginning_middle_end', ARRAY['remember', 'childhood', 'favorite', 'memory', 'used to', 'always', 'special'], ARRAY['یاد', 'بچپن', 'پسندیدہ', 'یاد', 'کرتا تھا', 'ہمیشہ', 'خاص'], 'I remember my favorite childhood memory was going to my grandmother''s house every summer. We used to play in her garden and she always made our favorite food. It was special because she told us stories and we felt so loved. Those summers were the happiest times of my childhood.', 'مجھے اپنے پسندیدہ بچپن کی یاد یہ ہے کہ ہر گرمیوں میں میں اپنی دادی کے گھر جاتا تھا۔ ہم ان کے باغ میں کھیلا کرتے تھے اور وہ ہمیشہ ہمارا پسندیدہ کھانا بناتی تھیں۔ یہ خاص تھا کیونکہ وہ ہمیں کہانیاں سناتی تھیں اور ہم خود کو بہت پیارا محسوس کرتے تھے۔ وہ گرمیاں میرے بچپن کے سب سے خوشگوار وقت تھے۔', '{"past_tense_usage": ["remember", "was", "used to", "made", "told", "felt", "were"], "narrative_structure": ["every summer", "we used to", "it was special because", "those summers"], "descriptive_language": ["favorite", "special", "loved", "happiest"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice past tense verbs and time-based storytelling', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Tell me about a time you helped someone.', 'مجھے ایک ایسے وقت کے بارے میں بتائیں جب آپ نے کسی کی مدد کی۔', 'helping_others', 'b1_intermediate', 'past_simple', 'beginning_middle_end', ARRAY['helped', 'someone', 'needed', 'support', 'felt good', 'grateful', 'kind'], ARRAY['مدد', 'کسی کی', 'ضرورت', 'سہارا', 'اچھا محسوس', 'شکر گزار', 'مہربان'], 'I helped my neighbor when she was sick last month. She needed someone to buy groceries for her family. I went to the market and got everything she needed. She was very grateful and felt good about helping. It made me realize how important it is to be kind to others.', 'میں نے اپنی پڑوسن کی مدد کی جب وہ پچھلے مہینے بیمار تھیں۔ انہیں اپنے خاندان کے لیے گروسری خریدنے کی ضرورت تھی۔ میں مارکیٹ گیا اور ان کی ضرورت کی ہر چیز لایا۔ وہ بہت شکر گزار تھیں اور مجھے مدد کرنے میں اچھا لگا۔ اس نے مجھے احساس دلایا کہ دوسروں کے ساتھ مہربان ہونا کتنا اہم ہے۔', '{"past_tense_usage": ["helped", "was", "needed", "went", "got", "was", "felt", "made"], "narrative_structure": ["when she was", "she needed", "I went", "it made me realize"], "descriptive_language": ["sick", "grateful", "good", "kind", "important"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice past tense verbs and time-based storytelling', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Describe a place you would like to visit.', 'ایک ایسی جگہ کی تفصیل بتائیں جہاں آپ جانا چاہیں گے۔', 'travel_dreams', 'b1_intermediate', 'future_simple', 'descriptive_narrative', ARRAY['would like', 'visit', 'dream', 'beautiful', 'interesting', 'culture', 'food'], ARRAY['جانا چاہیں گے', 'ملاحظہ', 'خواب', 'خوبصورت', 'دلچسپ', 'ثقافت', 'کھانا'], 'I would like to visit Japan someday. It''s a beautiful country with interesting culture and amazing food. I dream of seeing the cherry blossoms and trying authentic Japanese cuisine. The people are very polite and the technology is advanced. I think it would be an unforgettable experience.', 'میں کبھی جاپان جانا چاہوں گا۔ یہ ایک خوبصورت ملک ہے جس میں دلچسپ ثقافت اور حیرت انگیز کھانا ہے۔ میں چیری کے پھولوں کو دیکھنے اور اصل جاپانی کھانا کھانے کا خواب دیکھتا ہوں۔ لوگ بہت مہذب ہیں اور ٹیکنالوجی ترقی یافتہ ہے۔ مجھے لگتا ہے کہ یہ ایک ناقابل فراموش تجربہ ہوگا۔', '{"future_tense_usage": ["would like", "dream of", "would be"], "narrative_structure": ["someday", "I dream of", "I think it would be"], "descriptive_language": ["beautiful", "interesting", "amazing", "polite", "advanced", "unforgettable"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice future tense verbs and descriptive language', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Tell me about your future goals.', 'اپنے مستقبل کے اہداف کے بارے میں بتائیں۔', 'future_aspirations', 'b1_intermediate', 'future_simple', 'goal_setting_narrative', ARRAY['future', 'goals', 'want to', 'plan to', 'hope to', 'achieve', 'success'], ARRAY['مستقبل', 'اہداف', 'چاہتے', 'منصوبہ', 'امید', 'حاصل', 'کامیابی'], 'My future goals include getting a good job and traveling the world. I want to improve my English skills and plan to study abroad. I hope to achieve success in my career and make my family proud. I also plan to learn new languages and meet people from different cultures.', 'میرے مستقبل کے اہداف میں اچھی نوکری حاصل کرنا اور دنیا گھومنا شامل ہے۔ میں اپنی انگریزی مہارت کو بہتر بنانا چاہتا ہوں اور بیرون ملک پڑھنے کا منصوبہ ہے۔ مجھے امید ہے کہ میں اپنے کیریئر میں کامیابی حاصل کروں گا اور اپنے خاندان کو فخر دلاؤں گا۔ میں نئی زبانیں سیکھنے اور مختلف ثقافتوں کے لوگوں سے ملنے کا بھی منصوبہ رکھتا ہوں۔', '{"future_tense_usage": ["include", "want to", "plan to", "hope to", "will achieve"], "narrative_structure": ["my future goals include", "I want to", "I hope to", "I also plan to"], "descriptive_language": ["good", "improve", "success", "proud", "new", "different"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice future tense verbs and goal-setting language', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Describe a book or movie you enjoyed.', 'ایک کتاب یا فلم کی تفصیل بتائیں جو آپ نے پسند کی۔', 'entertainment_reviews', 'b1_intermediate', 'past_simple', 'review_narrative', ARRAY['enjoyed', 'book', 'movie', 'story', 'characters', 'plot', 'recommend'], ARRAY['پسند', 'کتاب', 'فلم', 'کہانی', 'کردار', 'پلاٹ', 'تجویز'], 'I enjoyed reading "The Alchemist" by Paulo Coelho. The story is about a young shepherd who travels to find his treasure. The characters are interesting and the plot is inspiring. I recommend this book because it teaches important life lessons about following your dreams.', 'مجھے پاؤلو کوئیلو کی "دی الکیمسٹ" پڑھنا پسند آیا۔ کہانی ایک نوجوان چرواہے کے بارے میں ہے جو اپنا خزانہ تلاش کرنے کے لیے سفر کرتا ہے۔ کردار دلچسپ ہیں اور پلاٹ متاثر کن ہے۔ میں اس کتاب کی سفارش کرتا ہوں کیونکہ یہ اپنے خوابوں کا پیچھا کرنے کے بارے میں اہم زندگی کے سبق سکھاتی ہے۔', '{"past_tense_usage": ["enjoyed", "is", "travels", "are", "is", "recommend", "teaches"], "narrative_structure": ["the story is about", "the characters are", "I recommend because"], "descriptive_language": ["interesting", "inspiring", "important", "life lessons"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice past tense verbs and descriptive language', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Tell me about a skill you want to learn.', 'ایک مہارت کے بارے میں بتائیں جو آپ سیکھنا چاہتے ہیں۔', 'learning_aspirations', 'b1_intermediate', 'future_simple', 'aspiration_narrative', ARRAY['want to learn', 'skill', 'interested in', 'practice', 'improve', 'useful', 'important'], ARRAY['سیکھنا چاہتے', 'مہارت', 'دلچسپی', 'مشق', 'بہتر', 'مفید', 'اہم'], 'I want to learn how to play the guitar. I''m interested in music and think it would be a useful skill. I plan to practice every day and improve my technique. It''s important to me because music brings people together and I want to be able to play for my family and friends.', 'میں گٹار بجانا سیکھنا چاہتا ہوں۔ مجھے موسیقی میں دلچسپی ہے اور مجھے لگتا ہے کہ یہ ایک مفید مہارت ہوگی۔ میں روزانہ مشق کرنے اور اپنی تکنیک بہتر بنانے کا منصوبہ رکھتا ہوں۔ میرے لیے یہ اہم ہے کیونکہ موسیقی لوگوں کو اکٹھا کرتی ہے اور میں اپنے خاندان اور دوستوں کے لیے بجانے کے قابل بننا چاہتا ہوں۔', '{"future_tense_usage": ["want to learn", "would be", "plan to", "will improve"], "narrative_structure": ["I want to learn", "I''m interested in", "I plan to", "it''s important because"], "descriptive_language": ["interested", "useful", "important", "brings together"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice future tense verbs and aspiration language', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']),
('Describe your ideal day.', 'اپنے مثالی دن کی تفصیل بتائیں۔', 'lifestyle_preferences', 'b1_intermediate', 'present_simple', 'descriptive_narrative', ARRAY['ideal', 'perfect', 'morning', 'afternoon', 'evening', 'relaxing', 'enjoyable'], ARRAY['مثالی', 'بہترین', 'صبح', 'دوپہر', 'شام', 'آرام دہ', 'لطف اندوز'], 'My ideal day would start with a peaceful morning walk in the park. In the afternoon, I would spend time with my family and have a delicious meal together. The evening would be relaxing with a good book or movie. It would be perfect if I could also call my friends and catch up with them. A day like this would be truly enjoyable.', 'میرا مثالی دن پارک میں پرسکون صبح کی سیر سے شروع ہوگا۔ دوپہر میں، میں اپنے خاندان کے ساتھ وقت گزاروں گا اور ایک لذیذ کھانا کھاؤں گا۔ شام ایک اچھی کتاب یا فلم کے ساتھ آرام دہ ہوگی۔ یہ بہترین ہوگا اگر میں اپنے دوستوں کو فون کر سکوں اور ان سے بات کر سکوں۔ اس طرح کا دن واقعی لطف اندوز ہوگا۔', '{"present_tense_usage": ["would start", "would spend", "would be", "would be perfect", "would be enjoyable"], "narrative_structure": ["would start with", "in the afternoon", "the evening would be", "it would be perfect if"], "descriptive_language": ["peaceful", "delicious", "relaxing", "perfect", "enjoyable"], "fluency_indicators": ["smooth_transitions", "appropriate_pacing", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Develop narrative fluency in English', 'Practice conditional tense and descriptive language', 'Gain confidence in speaking longer structured sentences', 'Learn storytelling transitions: First, Then, Finally']);

-- =============================================================================
-- STAGE 3 EXERCISE 2: GROUP DISCUSSION SIMULATION
-- =============================================================================

-- Table for Group Discussion Simulation
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage3_exercise2_group_discussion (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    title_urdu TEXT NOT NULL,
    context TEXT NOT NULL,
    context_urdu TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'b1_intermediate',
    category TEXT NOT NULL,
    conversation_flow TEXT NOT NULL,
    initial_prompt TEXT NOT NULL,
    initial_prompt_urdu TEXT NOT NULL,
    follow_up_turns JSONB NOT NULL,
    expected_responses JSONB NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    learning_objectives TEXT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for Group Discussion Simulation
INSERT INTO public.ai_tutor_stage3_exercise2_group_discussion (title, title_urdu, context, context_urdu, difficulty, category, conversation_flow, initial_prompt, initial_prompt_urdu, follow_up_turns, expected_responses, evaluation_criteria, learning_objectives) VALUES
('Planning a Weekend Trip', 'ہفتے کے آخر میں سفر کی منصوبہ بندی', 'You and your friends (AI) are planning a weekend trip.', 'آپ اور آپ کے دوست (AI) ہفتے کے آخر میں سفر کی منصوبہ بندی کر رہے ہیں۔', 'b1_intermediate', 'travel_planning', 'decision_making', 'Ali: Where should we go this weekend?', 'علی: ہمیں اس ہفتے کے آخر میں کہاں جانا چاہیے؟', '[{"speaker": "Sara", "message": "I think the beach would be fun! We could swim and have a picnic.", "message_urdu": "میں سوچتی ہوں کہ ساحل سمندر تفریحی ہوگا! ہم تیر سکتے ہیں اور پکنک کر سکتے ہیں۔", "intent": "suggestion_with_reason"}, {"speaker": "Ali", "message": "What do you think, [your name]? Should we go to the beach or somewhere else?", "message_urdu": "آپ کیا سوچتے ہیں، [آپ کا نام]؟ کیا ہمیں ساحل سمندر جانا چاہیے یا کہیں اور؟", "intent": "asking_for_opinion"}]', '[{"response": "I agree! The beach sounds perfect for a weekend trip.", "response_urdu": "میں متفق ہوں! ہفتے کے آخر میں سفر کے لیے ساحل سمندر بہترین لگتا ہے۔", "type": "agreement", "keywords": ["agree", "beach", "perfect", "weekend"]}, {"response": "That''s a great idea! I love swimming and picnics.", "response_urdu": "یہ ایک بہترین خیال ہے! مجھے تیراکی اور پکنک پسند ہے۔", "type": "agreement_with_enthusiasm", "keywords": ["great", "idea", "love", "swimming"]}, {"response": "Actually, I was thinking about the mountains. What do you think about hiking?", "response_urdu": "دراصل، میں پہاڑوں کے بارے میں سوچ رہا تھا۔ پیدل سفر کے بارے میں آپ کیا سوچتے ہیں؟", "type": "polite_disagreement_with_alternative", "keywords": ["actually", "mountains", "hiking", "think"]}]', '{"relevance_to_conversation": ["responds_to_question", "acknowledges_others", "contributes_meaningfully"], "appropriate_expressions": ["agreement_phrases", "disagreement_phrases", "opinion_phrases"], "fluency_and_tone": ["natural_flow", "polite_tone", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Practice group discussion skills', 'Learn to express opinions politely', 'Develop conversation flow management', 'Build confidence in group settings']),
('Choosing a Restaurant', 'ریستوران کا انتخاب', 'You and your colleagues are deciding where to have lunch.', 'آپ اور آپ کے ساتھی دوپہر کا کھانا کہاں کھائیں اس کا فیصلہ کر رہے ہیں۔', 'b1_intermediate', 'food_choices', 'decision_making', 'Sarah: Where should we go for lunch today?', 'سارہ: آج ہمیں دوپہر کا کھانا کہاں کھانا چاہیے؟', '[{"speaker": "Mike", "message": "How about that new Italian restaurant? I heard the pasta is amazing.", "message_urdu": "اس نئے اطالوی ریستوران کے بارے میں کیا خیال ہے؟ میں نے سنا ہے کہ پاستا حیرت انگیز ہے۔", "intent": "suggestion_with_reason"}, {"speaker": "Sarah", "message": "What do you prefer, [your name]? Italian food or something else?", "message_urdu": "آپ کیا ترجیح دیتے ہیں، [آپ کا نام]؟ اطالوی کھانا یا کچھ اور؟", "intent": "asking_for_preference"}]', '[{"response": "Italian sounds great! I love pasta and pizza.", "response_urdu": "اطالوی بہترین لگتا ہے! مجھے پاستا اور پیزا پسند ہے۔", "type": "agreement_with_enthusiasm", "keywords": ["sounds great", "love", "pasta", "pizza"]}, {"response": "Actually, I was thinking about Pakistani food. What about that new biryani place?", "response_urdu": "دراصل، میں پاکستانی کھانے کے بارے میں سوچ رہا تھا۔ اس نئے بریانی کے مقام کے بارے میں کیا خیال ہے؟", "type": "polite_disagreement_with_alternative", "keywords": ["actually", "Pakistani food", "biryani", "place"]}, {"response": "Either sounds good to me. I''m not picky about food.", "response_urdu": "دونوں مجھے اچھے لگتے ہیں۔ مجھے کھانے کے بارے میں کوئی پسند ناپسند نہیں۔", "type": "neutral_agreement", "keywords": ["either", "sounds good", "not picky"]}]', '{"relevance_to_conversation": ["responds_to_question", "acknowledges_others", "contributes_meaningfully"], "appropriate_expressions": ["agreement_phrases", "disagreement_phrases", "preference_phrases"], "fluency_and_tone": ["natural_flow", "polite_tone", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Practice group discussion skills', 'Learn to express preferences politely', 'Develop conversation flow management', 'Build confidence in group settings']),
('Planning a Birthday Party', 'سالگرہ کی پارٹی کی منصوبہ بندی', 'You and your friends are organizing a birthday party for your mutual friend.', 'آپ اور آپ کے دوست اپنے مشترکہ دوست کے لیے سالگرہ کی پارٹی کا اہتمام کر رہے ہیں۔', 'b1_intermediate', 'event_planning', 'collaborative_planning', 'Lisa: We need to plan Ahmed''s birthday party. What should we do?', 'لیسا: ہمیں احمد کی سالگرہ کی پارٹی کی منصوبہ بندی کرنی ہے۔ ہمیں کیا کرنا چاہیے؟', '[{"speaker": "Tom", "message": "I think we should have it at his house. It would be more personal and fun.", "message_urdu": "میں سوچتا ہوں کہ ہمیں اس کے گھر میں کرنی چاہیے۔ یہ زیادہ ذاتی اور تفریحی ہوگا۔", "intent": "suggestion_with_reason"}, {"speaker": "Lisa", "message": "What do you think, [your name]? Should we have it at his house or somewhere else?", "message_urdu": "آپ کیا سوچتے ہیں، [آپ کا نام]؟ کیا ہمیں اس کے گھر میں کرنی چاہیے یا کہیں اور؟", "intent": "asking_for_opinion"}]', '[{"response": "That''s a perfect idea! His house would be cozy and comfortable.", "response_urdu": "یہ ایک بہترین خیال ہے! اس کا گھر آرام دہ اور سکون بخش ہوگا۔", "type": "agreement_with_enthusiasm", "keywords": ["perfect", "idea", "cozy", "comfortable"]}, {"response": "Actually, I was thinking about a restaurant. It would be easier for everyone.", "response_urdu": "دراصل، میں ریستوران کے بارے میں سوچ رہا تھا۔ یہ سب کے لیے آسان ہوگا۔", "type": "polite_disagreement_with_alternative", "keywords": ["actually", "restaurant", "easier", "everyone"]}, {"response": "Either option sounds good. What matters most is that Ahmed has a great time.", "response_urdu": "دونوں اختیارات اچھے لگتے ہیں۔ سب سے اہم بات یہ ہے کہ احمد کا وقت اچھا گزرے۔", "type": "neutral_agreement_with_focus", "keywords": ["either", "option", "matters", "great time"]}]', '{"relevance_to_conversation": ["responds_to_question", "acknowledges_others", "contributes_meaningfully"], "appropriate_expressions": ["agreement_phrases", "disagreement_phrases", "opinion_phrases"], "fluency_and_tone": ["natural_flow", "polite_tone", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Practice group discussion skills', 'Learn to express opinions politely', 'Develop conversation flow management', 'Build confidence in group settings']),
('Discussing Weekend Activities', 'ہفتے کے آخر کی سرگرمیوں پر بات چیت', 'You and your family are discussing what to do this weekend.', 'آپ اور آپ کا خاندان اس ہفتے کے آخر میں کیا کرنا ہے اس پر بات چیت کر رہے ہیں۔', 'b1_intermediate', 'family_activities', 'decision_making', 'Mom: What should we do this weekend? Any ideas?', 'امی: اس ہفتے کے آخر میں ہمیں کیا کرنا چاہیے؟ کوئی خیال؟', '[{"speaker": "Dad", "message": "How about going to the zoo? The kids would love to see the animals.", "message_urdu": "چڑیا گھر جانے کے بارے میں کیا خیال ہے؟ بچوں کو جانور دیکھنا پسند آئے گا۔", "intent": "suggestion_with_reason"}, {"speaker": "Mom", "message": "What do you think, [your name]? Zoo or something else?", "message_urdu": "آپ کیا سوچتے ہیں، [آپ کا نام]؟ چڑیا گھر یا کچھ اور؟", "intent": "asking_for_opinion"}]', '[{"response": "The zoo sounds wonderful! I love seeing animals too.", "response_urdu": "چڑیا گھر بہترین لگتا ہے! مجھے بھی جانور دیکھنا پسند ہے۔", "type": "agreement_with_enthusiasm", "keywords": ["sounds wonderful", "love", "seeing", "animals"]}, {"response": "Actually, I was thinking about the park. It''s free and we can have a picnic.", "response_urdu": "دراصل، میں پارک کے بارے میں سوچ رہا تھا۔ یہ مفت ہے اور ہم پکنک کر سکتے ہیں۔", "type": "polite_disagreement_with_alternative", "keywords": ["actually", "park", "free", "picnic"]}, {"response": "Both sound great! I''m happy with whatever the family decides.", "response_urdu": "دونوں بہترین لگتے ہیں! خاندان جو بھی فیصلہ کرے، مجھے خوشی ہوگی۔", "type": "neutral_agreement", "keywords": ["both", "sound great", "happy", "decides"]}]', '{"relevance_to_conversation": ["responds_to_question", "acknowledges_others", "contributes_meaningfully"], "appropriate_expressions": ["agreement_phrases", "disagreement_phrases", "opinion_phrases"], "fluency_and_tone": ["natural_flow", "polite_tone", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Practice group discussion skills', 'Learn to express opinions politely', 'Develop conversation flow management', 'Build confidence in group settings']),
('Choosing a Movie', 'فلم کا انتخاب', 'You and your friends are deciding which movie to watch tonight.', 'آپ اور آپ کے دوست آج رات کون سی فلم دیکھنی ہے اس کا فیصلہ کر رہے ہیں۔', 'b1_intermediate', 'entertainment_choices', 'decision_making', 'Emma: What movie should we watch tonight?', 'ایما: آج رات ہمیں کون سی فلم دیکھنی چاہیے؟', '[{"speaker": "Jack", "message": "How about that new action movie? I heard it''s really exciting.", "message_urdu": "اس نئی ایکشن فلم کے بارے میں کیا خیال ہے؟ میں نے سنا ہے کہ یہ واقعی دلچسپ ہے۔", "intent": "suggestion_with_reason"}, {"speaker": "Emma", "message": "What do you prefer, [your name]? Action or comedy?", "message_urdu": "آپ کیا ترجیح دیتے ہیں، [آپ کا نام]؟ ایکشن یا کامیڈی؟", "intent": "asking_for_preference"}]', '[{"response": "Action sounds exciting! I love thrilling movies.", "response_urdu": "ایکشن دلچسپ لگتا ہے! مجھے سنسنی خیز فلمیں پسند ہیں۔", "type": "agreement_with_enthusiasm", "keywords": ["sounds exciting", "love", "thrilling", "movies"]}, {"response": "Actually, I prefer comedy. It would be more relaxing after a long day.", "response_urdu": "دراصل، مجھے کامیڈی پسند ہے۔ لمبے دن کے بعد یہ زیادہ آرام دہ ہوگا۔", "type": "polite_disagreement_with_alternative", "keywords": ["actually", "prefer", "comedy", "relaxing"]}, {"response": "Either is fine with me. I enjoy both genres.", "response_urdu": "دونوں میرے لیے ٹھیک ہیں۔ مجھے دونوں قسمیں پسند ہیں۔", "type": "neutral_agreement", "keywords": ["either", "fine", "enjoy", "both genres"]}]', '{"relevance_to_conversation": ["responds_to_question", "acknowledges_others", "contributes_meaningfully"], "appropriate_expressions": ["agreement_phrases", "disagreement_phrases", "preference_phrases"], "fluency_and_tone": ["natural_flow", "polite_tone", "clear_pronunciation"], "minimum_score": 75}', ARRAY['Practice group discussion skills', 'Learn to express preferences politely', 'Develop conversation flow management', 'Build confidence in group settings']);

-- =============================================================================
-- STAGE 3 EXERCISE 3: PROBLEM SOLVING CONVERSATIONS
-- =============================================================================

-- Table for Problem Solving Conversations
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage3_exercise3_problem_solving (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    title_urdu TEXT NOT NULL,
    problem_description TEXT NOT NULL,
    problem_description_urdu TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'b1_intermediate',
    category TEXT NOT NULL,
    scenario_type TEXT NOT NULL,
    context TEXT NOT NULL,
    context_urdu TEXT NOT NULL,
    expected_keywords TEXT[] NOT NULL,
    expected_keywords_urdu TEXT[] NOT NULL,
    polite_phrases TEXT[] NOT NULL,
    polite_phrases_urdu TEXT[] NOT NULL,
    sample_responses TEXT[] NOT NULL,
    sample_responses_urdu TEXT[] NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    learning_objectives TEXT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for Problem Solving Conversations
INSERT INTO public.ai_tutor_stage3_exercise3_problem_solving (title, title_urdu, problem_description, problem_description_urdu, difficulty, category, scenario_type, context, context_urdu, expected_keywords, expected_keywords_urdu, polite_phrases, polite_phrases_urdu, sample_responses, sample_responses_urdu, evaluation_criteria, learning_objectives) VALUES
('Phone Not Working - Customer Support', 'فون کام نہیں کر رہا - کسٹمر سپورٹ', 'Your phone is not working properly. You need to call customer support to get help.', 'آپ کا فون درست طریقے سے کام نہیں کر رہا۔ آپ کو مدد کے لیے کسٹمر سپورٹ کو فون کرنا ہے۔', 'b1_intermediate', 'customer_service', 'technical_issue', 'You bought a new phone last week, but it''s been having problems. The screen freezes, apps crash, and sometimes it doesn''t turn on. You need to call customer support to get it fixed or replaced.', 'آپ نے پچھلے ہفتے ایک نیا فون خریدا تھا، لیکن اس میں مسائل آ رہے ہیں۔ سکرین جم جاتی ہے، ایپس کریش ہو جاتی ہیں، اور کبھی کبھی یہ آن نہیں ہوتا۔ آپ کو اسے ٹھیک کرانے یا تبدیل کرانے کے لیے کسٹمر سپورٹ کو فون کرنا ہے۔', ARRAY['not working', 'problem', 'issue', 'help', 'please', 'fix', 'broken', 'customer support', 'technical', 'assistance'], ARRAY['کام نہیں کر رہا', 'مسئلہ', 'مدد', 'براہ کرم', 'ٹھیک کریں', 'خراب', 'کسٹمر سپورٹ', 'تکنیکی', 'مدد'], ARRAY['Could you please help me with...', 'I''m having trouble with...', 'I would appreciate if you could...', 'Would it be possible to...', 'I''m sorry to bother you, but...'], ARRAY['کیا آپ براہ کرم میری مدد کر سکتے ہیں...', 'مجھے مسئلہ آ رہا ہے...', 'میں شکر گزار ہوں گا اگر آپ...', 'کیا یہ ممکن ہے کہ...', 'معذرت، لیکن...'], ARRAY['Hi, I''m calling because my phone isn''t working properly. Could you please help me?', 'I''m having trouble with my new phone. The screen keeps freezing and apps crash. Can you assist me?', 'I bought this phone last week, but it''s not working correctly. Would it be possible to get it fixed or replaced?'], ARRAY['ہیلو، میں فون کر رہا ہوں کیونکہ میرا فون درست طریقے سے کام نہیں کر رہا۔ کیا آپ براہ کرم میری مدد کر سکتے ہیں؟', 'مجھے اپنے نئے فون کے ساتھ مسئلہ آ رہا ہے۔ سکرین جم جاتی ہے اور ایپس کریش ہو جاتی ہیں۔ کیا آپ میری مدد کر سکتے ہیں؟', 'میں نے یہ فون پچھلے ہفتے خریدا تھا، لیکن یہ درست طریقے سے کام نہیں کر رہا۔ کیا یہ ممکن ہے کہ اسے ٹھیک کیا جائے یا تبدیل کیا جائے؟'], '{"clarity": "Clear description of the problem and its symptoms", "politeness": "Use of polite phrases and respectful tone", "request_structure": "Proper way to ask for help or assistance", "specificity": "Providing specific details about the issue", "solution_oriented": "Asking for specific solutions or next steps"}', ARRAY['Learn polite problem-solving language', 'Practice functional English for daily use', 'Build confidence in requesting help professionally', 'Use appropriate customer service vocabulary']),
('Lost Wallet - Police Station', 'پرس گم - پولیس اسٹیشن', 'You lost your wallet and need to report it to the police.', 'آپ کا پرس گم ہو گیا ہے اور آپ کو اس کی رپورٹ پولیس میں کرنی ہے۔', 'b1_intermediate', 'emergency_services', 'lost_property', 'You were shopping at the mall yesterday and realized your wallet is missing. It contained your ID, credit cards, and some cash. You need to report this to the police station.', 'آپ کل مال میں خریداری کر رہے تھے اور آپ کو احساس ہوا کہ آپ کا پرس گم ہے۔ اس میں آپ کی شناخت، کریڈٹ کارڈز، اور کچھ نقد رقم تھی۔ آپ کو یہ پولیس اسٹیشن میں رپورٹ کرنا ہے۔', ARRAY['lost', 'wallet', 'missing', 'report', 'police', 'stolen', 'help', 'please', 'important', 'documents'], ARRAY['گم', 'پرس', 'لاپتہ', 'رپورٹ', 'پولیس', 'چوری', 'مدد', 'براہ کرم', 'اہم', 'دستاویزات'], ARRAY['I need to report a lost item', 'Could you help me file a report?', 'I would like to report that...', 'This is very important to me', 'Could you please assist me?'], ARRAY['مجھے گم شدہ چیز کی رپورٹ کرنی ہے', 'کیا آپ میری رپورٹ فائل کرنے میں مدد کر سکتے ہیں؟', 'میں رپورٹ کرنا چاہتا ہوں کہ...', 'یہ میرے لیے بہت اہم ہے', 'کیا آپ براہ کرم میری مدد کر سکتے ہیں؟'], ARRAY['Hello, I need to report that my wallet is missing. Could you help me file a report?', 'I lost my wallet yesterday at the mall. It contained my ID and credit cards. This is very important to me.', 'Could you please help me report a lost wallet? I think it might have been stolen.'], ARRAY['ہیلو، مجھے رپورٹ کرنی ہے کہ میرا پرس لاپتہ ہے۔ کیا آپ میری رپورٹ فائل کرنے میں مدد کر سکتے ہیں؟', 'میں نے کل مال میں اپنا پرس کھو دیا۔ اس میں میری شناخت اور کریڈٹ کارڈز تھے۔ یہ میرے لیے بہت اہم ہے۔', 'کیا آپ براہ کرم میری مدد کر سکتے ہیں کہ میں گم شدہ پرس کی رپورٹ کروں؟ مجھے لگتا ہے کہ یہ چوری ہو گیا ہوگا۔'], '{"clarity": "Clear description of what was lost and when", "politeness": "Use of polite phrases and respectful tone", "request_structure": "Proper way to ask for help with reporting", "specificity": "Providing specific details about the lost item", "urgency": "Conveying the importance of the situation"}', ARRAY['Learn emergency service communication', 'Practice reporting lost items professionally', 'Build confidence in dealing with authorities', 'Use appropriate police station vocabulary']),
('Internet Connection Issues - Technical Support', 'انٹرنیٹ کنکشن کے مسائل - تکنیکی سپورٹ', 'Your internet is not working and you need to call technical support.', 'آپ کا انٹرنیٹ کام نہیں کر رہا اور آپ کو تکنیکی سپورٹ کو فون کرنا ہے۔', 'b1_intermediate', 'technical_support', 'connectivity_issue', 'Your home internet has been down for two days. You work from home and need it urgently. You''ve tried restarting the router but it still doesn''t work. You need to call your internet provider for technical support.', 'آپ کا گھریلو انٹرنیٹ دو دن سے بند ہے۔ آپ گھر سے کام کرتے ہیں اور اس کی فوری ضرورت ہے۔ آپ نے روٹر ری اسٹارٹ کرنے کی کوشش کی ہے لیکن یہ اب بھی کام نہیں کر رہا۔ آپ کو اپنے انٹرنیٹ فراہم کنندہ کو تکنیکی سپورٹ کے لیے فون کرنا ہے۔', ARRAY['internet', 'connection', 'not working', 'down', 'router', 'technical support', 'urgent', 'help', 'please', 'fix'], ARRAY['انٹرنیٹ', 'کنکشن', 'کام نہیں کر رہا', 'بند', 'روٹر', 'تکنیکی سپورٹ', 'فوری', 'مدد', 'براہ کرم', 'ٹھیک'], ARRAY['I''m having internet connectivity issues', 'Could you please help me troubleshoot?', 'This is urgent for my work', 'I need technical assistance', 'Could you send someone to fix this?'], ARRAY['مجھے انٹرنیٹ کنکشن کے مسائل آ رہے ہیں', 'کیا آپ براہ کرم میری مدد کر سکتے ہیں؟', 'یہ میرے کام کے لیے فوری ہے', 'مجھے تکنیکی مدد چاہیے', 'کیا آپ کوئی بھیج سکتے ہیں جو اسے ٹھیک کرے؟'], ARRAY['Hello, I''m calling about my internet connection. It''s been down for two days and I need it urgently for work.', 'I''m having trouble with my internet. I''ve tried restarting the router but it still doesn''t work. Could you help me?', 'Could you please send a technician? My internet has been down and this is affecting my work.'], ARRAY['ہیلو، میں اپنے انٹرنیٹ کنکشن کے بارے میں فون کر رہا ہوں۔ یہ دو دن سے بند ہے اور مجھے کام کے لیے فوری ضرورت ہے۔', 'مجھے انٹرنیٹ کے ساتھ مسئلہ آ رہا ہے۔ میں نے روٹر ری اسٹارٹ کرنے کی کوشش کی ہے لیکن یہ اب بھی کام نہیں کر رہا۔ کیا آپ میری مدد کر سکتے ہیں؟', 'کیا آپ براہ کرم ایک ٹیکنیشین بھیج سکتے ہیں؟ میرا انٹرنیٹ بند ہے اور یہ میرے کام کو متاثر کر رہا ہے۔'], '{"clarity": "Clear description of the technical problem", "politeness": "Use of polite phrases and respectful tone", "request_structure": "Proper way to ask for technical assistance", "urgency": "Conveying the urgency of the situation", "solution_oriented": "Asking for specific solutions or technician visit"}', ARRAY['Learn technical support communication', 'Practice describing technical problems clearly', 'Build confidence in requesting technical help', 'Use appropriate technical vocabulary']),
('Flight Delay - Airport Customer Service', 'پرواز میں تاخیر - ہوائی اڈے کی کسٹمر سروس', 'Your flight is delayed and you need to speak with customer service.', 'آپ کی پرواز میں تاخیر ہے اور آپ کو کسٹمر سروس سے بات کرنی ہے۔', 'b1_intermediate', 'travel_services', 'flight_delay', 'You''re at the airport and your flight has been delayed by 3 hours. You have an important meeting tomorrow and need to know your options. You need to speak with the airline customer service desk.', 'آپ ہوائی اڈے پر ہیں اور آپ کی پرواز میں 3 گھنٹے کی تاخیر ہے۔ آپ کے پاس کل ایک اہم میٹنگ ہے اور آپ کو اپنے اختیارات جاننے کی ضرورت ہے۔ آپ کو ایئر لائن کی کسٹمر سروس ڈیسک سے بات کرنی ہے۔', ARRAY['flight', 'delayed', 'delay', 'important', 'meeting', 'options', 'help', 'please', 'urgent', 'schedule'], ARRAY['پرواز', 'تاخیر', 'اہم', 'میٹنگ', 'اختیارات', 'مدد', 'براہ کرم', 'فوری', 'شیڈول'], ARRAY['I need to speak with someone about my delayed flight', 'Could you help me with my travel arrangements?', 'This is urgent for my business trip', 'What are my options?', 'Could you please assist me?'], ARRAY['مجھے اپنی تاخیر زدہ پرواز کے بارے میں کسی سے بات کرنی ہے', 'کیا آپ میرے سفر کے انتظامات میں میری مدد کر سکتے ہیں؟', 'یہ میرے کاروباری سفر کے لیے فوری ہے', 'میرے اختیارات کیا ہیں؟', 'کیا آپ براہ کرم میری مدد کر سکتے ہیں؟'], ARRAY['Hello, my flight has been delayed and I have an important meeting tomorrow. Could you help me?', 'I need to know my options for this delayed flight. This is urgent for my business trip.', 'Could you please tell me what I can do about this delay? I have a meeting I can''t miss.'], ARRAY['ہیلو، میری پرواز میں تاخیر ہے اور میرے پاس کل ایک اہم میٹنگ ہے۔ کیا آپ میری مدد کر سکتے ہیں؟', 'مجھے اس تاخیر زدہ پرواز کے لیے اپنے اختیارات جاننے کی ضرورت ہے۔ یہ میرے کاروباری سفر کے لیے فوری ہے۔', 'کیا آپ براہ کرم مجھے بتا سکتے ہیں کہ اس تاخیر کے بارے میں میں کیا کر سکتا ہوں؟ میرے پاس ایک میٹنگ ہے جسے میں نہیں چھوڑ سکتا۔'], '{"clarity": "Clear description of the travel situation", "politeness": "Use of polite phrases and respectful tone", "request_structure": "Proper way to ask for travel assistance", "urgency": "Conveying the urgency of the situation", "solution_oriented": "Asking for specific travel options"}', ARRAY['Learn travel service communication', 'Practice dealing with flight delays professionally', 'Build confidence in requesting travel assistance', 'Use appropriate airline vocabulary']),
('Bank Account Issue - Bank Customer Service', 'بینک اکاؤنٹ کا مسئلہ - بینک کی کسٹمر سروس', 'You have an issue with your bank account and need to call customer service.', 'آپ کے بینک اکاؤنٹ میں مسئلہ ہے اور آپ کو کسٹمر سروس کو فون کرنا ہے۔', 'b1_intermediate', 'financial_services', 'account_issue', 'You tried to withdraw money from an ATM but the transaction was declined. You know you have money in your account. You need to call your bank''s customer service to resolve this issue.', 'آپ نے اے ٹی ایم سے پیسے نکالنے کی کوشش کی لیکن لین دین مسترد ہو گیا۔ آپ جانتے ہیں کہ آپ کے اکاؤنٹ میں پیسے ہیں۔ آپ کو اس مسئلے کو حل کرنے کے لیے اپنے بینک کی کسٹمر سروس کو فون کرنا ہے۔', ARRAY['bank', 'account', 'transaction', 'declined', 'withdraw', 'money', 'help', 'please', 'issue', 'resolve'], ARRAY['بینک', 'اکاؤنٹ', 'لین دین', 'مسترد', 'نکالنا', 'پیسے', 'مدد', 'براہ کرم', 'مسئلہ', 'حل'], ARRAY['I''m having trouble with my bank account', 'Could you please help me resolve this issue?', 'My transaction was declined but I have money in my account', 'I need assistance with my account', 'Could you please check my account status?'], ARRAY['مجھے اپنے بینک اکاؤنٹ کے ساتھ مسئلہ آ رہا ہے', 'کیا آپ براہ کرم میری مدد کر سکتے ہیں کہ میں اس مسئلے کو حل کروں؟', 'میرا لین دین مسترد ہو گیا لیکن میرے اکاؤنٹ میں پیسے ہیں', 'مجھے اپنے اکاؤنٹ کے ساتھ مدد چاہیے', 'کیا آپ براہ کرم میرا اکاؤنٹ اسٹیٹس چیک کر سکتے ہیں؟'], ARRAY['Hello, I''m calling about my bank account. My ATM transaction was declined but I know I have money in my account.', 'I need help with my account. My withdrawal was declined and I don''t understand why.', 'Could you please check my account? I tried to withdraw money but the transaction was declined.'], ARRAY['ہیلو، میں اپنے بینک اکاؤنٹ کے بارے میں فون کر رہا ہوں۔ میرا اے ٹی ایم لین دین مسترد ہو گیا لیکن مجھے معلوم ہے کہ میرے اکاؤنٹ میں پیسے ہیں۔', 'مجھے اپنے اکاؤنٹ کے ساتھ مدد چاہیے۔ میرا پیسے نکالنے کا لین دین مسترد ہو گیا اور مجھے سمجھ نہیں آ رہا کہ کیوں۔', 'کیا آپ براہ کرم میرا اکاؤنٹ چیک کر سکتے ہیں؟ میں نے پیسے نکالنے کی کوشش کی لیکن لین دین مسترد ہو گیا۔'], '{"clarity": "Clear description of the banking issue", "politeness": "Use of polite phrases and respectful tone", "request_structure": "Proper way to ask for banking assistance", "specificity": "Providing specific details about the transaction", "solution_oriented": "Asking for account verification and resolution"}', ARRAY['Learn banking service communication', 'Practice describing financial issues clearly', 'Build confidence in requesting banking assistance', 'Use appropriate banking vocabulary']);

-- =============================================================================
-- INDEXES FOR PERFORMANCE
-- =============================================================================

-- Indexes for Storytelling Narration
CREATE INDEX IF NOT EXISTS idx_storytelling_category ON public.ai_tutor_stage3_exercise1_storytelling(category);
CREATE INDEX IF NOT EXISTS idx_storytelling_difficulty ON public.ai_tutor_stage3_exercise1_storytelling(difficulty);
CREATE INDEX IF NOT EXISTS idx_storytelling_tense ON public.ai_tutor_stage3_exercise1_storytelling(tense_focus);

-- Indexes for Group Discussion Simulation
CREATE INDEX IF NOT EXISTS idx_group_discussion_category ON public.ai_tutor_stage3_exercise2_group_discussion(category);
CREATE INDEX IF NOT EXISTS idx_group_discussion_difficulty ON public.ai_tutor_stage3_exercise2_group_discussion(difficulty);
CREATE INDEX IF NOT EXISTS idx_group_discussion_flow ON public.ai_tutor_stage3_exercise2_group_discussion(conversation_flow);

-- Indexes for Problem Solving Conversations
CREATE INDEX IF NOT EXISTS idx_problem_solving_category ON public.ai_tutor_stage3_exercise3_problem_solving(category);
CREATE INDEX IF NOT EXISTS idx_problem_solving_difficulty ON public.ai_tutor_stage3_exercise3_problem_solving(difficulty);
CREATE INDEX IF NOT EXISTS idx_problem_solving_type ON public.ai_tutor_stage3_exercise3_problem_solving(scenario_type);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE public.ai_tutor_stage3_exercise1_storytelling ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_tutor_stage3_exercise2_group_discussion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_tutor_stage3_exercise3_problem_solving ENABLE ROW LEVEL SECURITY;

-- RLS Policies for public access (these are content tables, not user-specific)
CREATE POLICY "Anyone can view storytelling narration" ON public.ai_tutor_stage3_exercise1_storytelling FOR SELECT USING (true);
CREATE POLICY "Anyone can view group discussion simulation" ON public.ai_tutor_stage3_exercise2_group_discussion FOR SELECT USING (true);
CREATE POLICY "Anyone can view problem solving conversations" ON public.ai_tutor_stage3_exercise3_problem_solving FOR SELECT USING (true);

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

-- Grant permissions for all tables
GRANT ALL ON public.ai_tutor_stage3_exercise1_storytelling TO anon, authenticated;
GRANT ALL ON public.ai_tutor_stage3_exercise2_group_discussion TO anon, authenticated;
GRANT ALL ON public.ai_tutor_stage3_exercise3_problem_solving TO anon, authenticated;

-- Grant permissions for sequences
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Verify data insertion
SELECT 'Storytelling Narration' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage3_exercise1_storytelling
UNION ALL
SELECT 'Group Discussion Simulation' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage3_exercise2_group_discussion
UNION ALL
SELECT 'Problem Solving Conversations' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage3_exercise3_problem_solving;

-- Sample data verification
SELECT 'Sample Storytelling Narration:' as info;
SELECT id, prompt, prompt_urdu, category FROM public.ai_tutor_stage3_exercise1_storytelling LIMIT 3;

SELECT 'Sample Group Discussion Simulation:' as info;
SELECT id, title, title_urdu, category FROM public.ai_tutor_stage3_exercise2_group_discussion LIMIT 3;

SELECT 'Sample Problem Solving Conversations:' as info;
SELECT id, title, title_urdu, category FROM public.ai_tutor_stage3_exercise3_problem_solving LIMIT 3;
