-- =============================================================================
-- AI English Tutor - Stage 6 Exercises Database Schema
-- =============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- STAGE 6 EXERCISE 1: ADVANCED SPONTANEOUS SPEAKING
-- =============================================================================

-- Table for Advanced Spontaneous Speaking
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage6_exercise1_spontaneous_speaking (
    id SERIAL PRIMARY KEY,
    topic TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'C2',
    topic_type TEXT NOT NULL,
    expected_structure TEXT NOT NULL,
    expected_keywords TEXT[] NOT NULL,
    vocabulary_focus TEXT[] NOT NULL,
    model_response TEXT NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for Advanced Spontaneous Speaking
INSERT INTO public.ai_tutor_stage6_exercise1_spontaneous_speaking (topic, category, difficulty, topic_type, expected_structure, expected_keywords, vocabulary_focus, model_response, evaluation_criteria) VALUES
('The importance of boredom in fostering creativity and innovation', 'Philosophical', 'C2', 'Abstract Reflection', 'Definition → Paradox → Benefits → Examples → Conclusion', ARRAY['creativity', 'focus', 'mindfulness', 'productivity', 'innovation', 'reflection', 'mental space', 'inspiration', 'contemplation', 'breakthrough'], ARRAY['cognitive rest', 'mental incubation', 'creative breakthrough', 'mindful awareness', 'intellectual stimulation', 'cognitive processing', 'mental clarity', 'innovative thinking', 'contemplative practice', 'creative potential'], 'Boredom, often dismissed as a negative state, actually serves as a crucial catalyst for creativity and innovation. When we''re bored, our minds are freed from the constant stimulation that characterizes modern life, allowing for deeper cognitive processing and creative incubation. This paradoxical relationship between boredom and creativity stems from the brain''s need for mental rest to process information and generate novel connections. During periods of boredom, our minds wander into uncharted territories, making unexpected associations that can lead to breakthrough ideas. History is replete with examples of great innovations emerging from moments of apparent inactivity—Einstein''s theory of relativity, Newton''s laws of motion, and countless artistic masterpieces. The key lies in embracing boredom as a form of cognitive rest rather than avoiding it through constant distraction. In our hyperconnected world, the ability to sit with boredom and allow the mind to wander freely has become a rare and valuable skill that directly correlates with creative output and innovative thinking.', '{"spontaneous_fluency": 30, "depth_of_thought": 25, "advanced_vocabulary": 25, "structural_coherence": 20}'),
('Describe a future world where money has been completely replaced by alternative value systems', 'Imaginative', 'C2', 'Futuristic Speculation', 'Current Problems → Alternative Systems → Implementation → Benefits → Challenges', ARRAY['trade', 'value', 'technology', 'economy', 'sustainability', 'community', 'resources', 'exchange', 'innovation', 'society'], ARRAY['post-scarcity economy', 'resource-based economy', 'contribution tracking', 'skill-based exchange', 'sustainable development', 'community reciprocity', 'value creation', 'economic transformation', 'social innovation', 'alternative currency'], 'In this future world, money has been replaced by sophisticated systems that track and reward genuine value creation rather than arbitrary financial metrics. The foundation rests on advanced AI systems that monitor individual contributions to society—whether through innovation, care work, environmental stewardship, or knowledge sharing. People earn ''impact credits'' based on their positive contributions to community wellbeing, environmental sustainability, and human development. The system operates through blockchain-like technology that ensures transparency and prevents gaming, while machine learning algorithms continuously optimize the allocation of resources based on real needs rather than market speculation. This creates a post-scarcity economy where basic needs are guaranteed, and people are motivated by purpose rather than profit. The transition required massive technological infrastructure, universal education about the new system, and careful phasing to prevent economic collapse. While challenges remain—such as defining what constitutes ''value'' and preventing new forms of inequality—the system has led to unprecedented levels of innovation, environmental restoration, and social cohesion.', '{"spontaneous_fluency": 30, "depth_of_thought": 25, "advanced_vocabulary": 25, "structural_coherence": 20}'),
('Why should governments prioritize funding for the arts over other public services?', 'Debate', 'C2', 'Policy Argument', 'Thesis → Cultural Value → Economic Impact → Social Benefits → Counterarguments → Conclusion', ARRAY['culture', 'support', 'expression', 'public', 'funding', 'society', 'development', 'identity', 'innovation', 'wellbeing'], ARRAY['cultural infrastructure', 'creative economy', 'social cohesion', 'cultural identity', 'artistic expression', 'public investment', 'cultural capital', 'creative industries', 'social innovation', 'cultural diplomacy'], 'Governments should prioritize arts funding because it serves as the foundation for cultural infrastructure that benefits society in ways that other public services cannot replicate. The arts provide essential cultural capital that strengthens social cohesion, fosters innovation across all sectors, and contributes significantly to economic development through the creative industries. Unlike traditional public services that address immediate needs, arts funding creates long-term value by preserving cultural identity, promoting cross-cultural understanding, and developing the creative thinking skills necessary for solving complex societal challenges. The economic argument is compelling—creative industries generate substantial revenue, create jobs, and attract tourism, while the social benefits include improved mental health, reduced crime rates, and enhanced community engagement. While critics argue that basic services should take precedence, this creates a false dichotomy. Arts funding is not merely a luxury but an investment in the cultural and intellectual infrastructure that makes other public services more effective. The arts teach us to think critically, empathize with others, and imagine alternative futures—skills essential for addressing the complex challenges facing modern societies.', '{"spontaneous_fluency": 30, "depth_of_thought": 25, "advanced_vocabulary": 25, "structural_coherence": 20}'),
('The role of failure in personal and professional development', 'Reflective', 'C2', 'Personal Philosophy', 'Definition → Learning Process → Examples → Growth → Application', ARRAY['failure', 'growth', 'learning', 'resilience', 'development', 'success', 'experience', 'improvement', 'adaptation', 'wisdom'], ARRAY['resilience building', 'growth mindset', 'experiential learning', 'adaptive capacity', 'cognitive flexibility', 'emotional intelligence', 'strategic thinking', 'risk assessment', 'continuous improvement', 'wisdom acquisition'], 'Failure serves as the most effective teacher in both personal and professional development, providing insights that success cannot offer. The learning process through failure involves cognitive restructuring, where our mental models are challenged and refined based on real-world feedback. This process builds resilience, enhances problem-solving abilities, and develops the adaptive capacity necessary for navigating complex, uncertain environments. History''s most successful individuals—from entrepreneurs to scientists to artists—attribute their achievements not to avoiding failure, but to learning from it systematically. The key lies in developing a growth mindset that views failure as data rather than judgment, allowing us to extract valuable lessons while maintaining motivation and confidence. This approach transforms setbacks into stepping stones, building the wisdom and strategic thinking required for long-term success. The most valuable failures are those that occur in environments where we can safely experiment and learn, highlighting the importance of creating cultures that encourage calculated risk-taking and honest reflection on outcomes.', '{"spontaneous_fluency": 30, "depth_of_thought": 25, "advanced_vocabulary": 25, "structural_coherence": 20}'),
('The impact of artificial intelligence on human creativity and artistic expression', 'Technological', 'C2', 'Future Analysis', 'Current State → Collaboration → Enhancement → Challenges → Future Vision', ARRAY['artificial intelligence', 'creativity', 'artistic', 'expression', 'technology', 'human', 'collaboration', 'innovation', 'potential', 'evolution'], ARRAY['human-AI collaboration', 'creative augmentation', 'artistic innovation', 'cognitive enhancement', 'creative potential', 'technological evolution', 'artistic expression', 'creative agency', 'digital transformation', 'creative intelligence'], 'Artificial intelligence is fundamentally transforming human creativity and artistic expression, not by replacing human artists, but by augmenting their creative capabilities and expanding the boundaries of what''s possible. The most compelling aspect of this transformation is the emergence of human-AI collaboration, where AI tools serve as creative partners that can handle technical execution while humans focus on conceptual vision and emotional depth. This collaboration enhances human creativity by removing technical barriers, enabling artists to explore new mediums and techniques that would otherwise be inaccessible. AI can generate variations, suggest alternatives, and handle repetitive tasks, freeing human creators to focus on higher-order creative decisions and emotional expression. However, this relationship raises profound questions about creative agency, authenticity, and the nature of artistic expression. The challenge lies in maintaining human intentionality and emotional resonance while leveraging AI''s computational power. The future of artistic expression likely involves a new form of creative intelligence that combines human intuition and emotional intelligence with AI''s pattern recognition and generative capabilities, creating art forms that neither humans nor AI could produce independently.', '{"spontaneous_fluency": 30, "depth_of_thought": 25, "advanced_vocabulary": 25, "structural_coherence": 20}');

-- =============================================================================
-- STAGE 6 EXERCISE 2: ADVANCED DIPLOMATIC COMMUNICATION
-- =============================================================================

-- Table for Advanced Diplomatic Communication
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage6_exercise2_diplomatic_communication (
    id SERIAL PRIMARY KEY,
    scenario TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'C2',
    scenario_type TEXT NOT NULL,
    context TEXT NOT NULL,
    stakeholder_emotions TEXT NOT NULL,
    expected_structure TEXT NOT NULL,
    expected_keywords TEXT[] NOT NULL,
    vocabulary_focus TEXT[] NOT NULL,
    model_response TEXT NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for Advanced Diplomatic Communication
INSERT INTO public.ai_tutor_stage6_exercise2_diplomatic_communication (scenario, category, difficulty, scenario_type, context, stakeholder_emotions, expected_structure, expected_keywords, vocabulary_focus, model_response, evaluation_criteria) VALUES
('You''re a team leader giving critical feedback to a colleague who has been underperforming for several months, affecting team morale and project deadlines.', 'Professional Feedback', 'C2', 'Performance Management', 'One-on-one meeting in private office', 'Defensive, anxious, potentially embarrassed', 'Opening → Specific Concerns → Impact → Support → Action Plan → Follow-up', ARRAY['feedback', 'performance', 'concerns', 'support', 'improvement', 'expectations', 'collaboration', 'development', 'timeline', 'resources'], ARRAY['constructive feedback', 'performance improvement', 'professional development', 'collaborative approach', 'supportive environment', 'clear expectations', 'developmental goals', 'performance metrics', 'professional growth', 'accountability'], 'I appreciate you taking the time to meet with me today. I want to have an open, constructive conversation about some concerns I''ve observed regarding your recent performance. Over the past few months, I''ve noticed that project deadlines have been consistently missed, and the quality of deliverables has fallen below our team''s standards. This has created challenges for the entire team and affected our ability to meet client expectations. I want to emphasize that this isn''t about placing blame, but rather about understanding what''s happening and how we can work together to address these issues. I''m committed to supporting your professional development and ensuring you have the resources and guidance you need to succeed. What factors do you think might be contributing to these challenges? I''d like to hear your perspective so we can develop a collaborative action plan that addresses both the immediate concerns and sets you up for long-term success.', '{"tone_control": 30, "empathy_authority_balance": 25, "clarity_communication": 25, "conflict_resolution": 20}'),
('You''re canceling plans with a close friend who has been looking forward to the event for weeks and is known to be very sensitive about rejection.', 'Personal Relationships', 'C2', 'Social Diplomacy', 'Phone call or in-person conversation', 'Disappointed, hurt, potentially angry', 'Acknowledgment → Explanation → Apology → Alternative → Reassurance', ARRAY['sorry', 'understand', 'disappointment', 'reschedule', 'important', 'unforeseen', 'commitment', 'priority', 'alternative', 'appreciation'], ARRAY['genuine apology', 'unforeseen circumstances', 'prior commitment', 'alternative arrangement', 'mutual understanding', 'relationship preservation', 'emotional sensitivity', 'compromise solution', 'future commitment', 'appreciation'], 'I feel terrible about this, and I know how much you''ve been looking forward to our plans. I want you to know that canceling is absolutely the last thing I want to do, and I understand how disappointing this must be for you. An urgent family matter has come up that requires my immediate attention, and I simply can''t postpone it. I''m genuinely sorry for any hurt or disappointment this causes you. I''d really like to reschedule for next week if that works for you, and I''m happy to be flexible with the timing to make it work. I value our friendship tremendously, and I hope you understand that this decision wasn''t made lightly. I''m committed to making this up to you and ensuring we have the quality time together that we both deserve.', '{"tone_control": 30, "empathy_authority_balance": 25, "clarity_communication": 25, "conflict_resolution": 20}'),
('You received poor service at an expensive restaurant and need to speak to the manager about your disappointing experience.', 'Customer Service', 'C2', 'Service Complaint', 'Restaurant, speaking with manager', 'Defensive, potentially dismissive', 'Calm Opening → Specific Issues → Impact → Expectations → Resolution', ARRAY['disappointed', 'experience', 'expectation', 'service', 'quality', 'resolution', 'professional', 'standards', 'improvement', 'satisfaction'], ARRAY['service quality', 'customer experience', 'professional standards', 'constructive feedback', 'service improvement', 'customer satisfaction', 'professional demeanor', 'resolution approach', 'quality assurance', 'service excellence'], 'I appreciate you taking the time to speak with me. I wanted to share some feedback about our dining experience this evening, as I believe it''s important for your team to understand how to improve service quality. We''ve been regular customers here and have always enjoyed the exceptional service and food quality. However, tonight''s experience fell significantly below the standards we''ve come to expect. The food arrived cold, our server was inattentive despite the restaurant not being busy, and when we raised concerns, they were dismissed rather than addressed. I''m sharing this feedback because I value this establishment and want to see it maintain its reputation for excellence. I''m not looking for compensation, but I do hope you''ll use this feedback to improve training and service standards. I believe in giving businesses the opportunity to address concerns professionally, which is why I''m speaking with you directly rather than simply not returning.', '{"tone_control": 30, "empathy_authority_balance": 25, "clarity_communication": 25, "conflict_resolution": 20}'),
('You''re rejecting a job offer from a company you respect, but need to maintain professional relationships for future opportunities.', 'Professional Networking', 'C2', 'Job Offer Decline', 'Phone call or in-person meeting', 'Disappointed, potentially frustrated', 'Gratitude → Decision → Reasoning → Future Interest → Professional Closure', ARRAY['appreciate', 'grateful', 'opportunity', 'decision', 'career', 'future', 'professional', 'relationship', 'consideration', 'respect'], ARRAY['professional gratitude', 'career alignment', 'future opportunities', 'professional relationship', 'careful consideration', 'mutual respect', 'professional courtesy', 'network preservation', 'career development', 'professional integrity'], 'I want to express my sincere gratitude for the job offer and the confidence you''ve shown in my abilities. This was not an easy decision, and I''ve given it careful consideration over the past week. After thorough reflection on my career goals and the role requirements, I''ve decided to decline the offer. This decision is based on my current career trajectory and personal circumstances, not on any concerns about the company or the position itself. I have tremendous respect for your organization and the work you do, and I hope to maintain our professional relationship. I would be very interested in future opportunities that might align better with my career goals, and I''d be happy to recommend qualified candidates for this position. I appreciate your understanding and hope this decision doesn''t impact our professional relationship moving forward.', '{"tone_control": 30, "empathy_authority_balance": 25, "clarity_communication": 25, "conflict_resolution": 20}'),
('You need to tell a close colleague that their idea for a major project has been rejected by senior management, and you were part of the decision-making process.', 'Professional Communication', 'C2', 'Bad News Delivery', 'Private office meeting', 'Disappointed, potentially betrayed, defensive', 'Direct Opening → Decision Context → Reasoning → Support → Future Opportunities', ARRAY['decision', 'management', 'consideration', 'factors', 'support', 'future', 'opportunities', 'contribution', 'valuable', 'development'], ARRAY['decision transparency', 'strategic considerations', 'professional support', 'future collaboration', 'valuable contribution', 'professional development', 'strategic alignment', 'organizational priorities', 'professional growth', 'collaborative approach'], 'I wanted to speak with you directly about the project proposal you submitted. After careful consideration by the senior management team, including myself, the decision has been made not to move forward with the project at this time. I want to be transparent about the factors that influenced this decision, which included budget constraints, strategic priorities, and timing considerations. Your idea was creative and well-thought-out, and I personally found many aspects of it compelling. I want you to know that this decision doesn''t reflect on your capabilities or the quality of your work. I''m committed to supporting your professional development and would be happy to work with you on future projects that align with our strategic priorities. Your innovative thinking is valuable to our team, and I hope we can collaborate on other initiatives that have strong potential for implementation.', '{"tone_control": 30, "empathy_authority_balance": 25, "clarity_communication": 25, "conflict_resolution": 20}');

-- =============================================================================
-- STAGE 6 EXERCISE 3: ADVANCED ACADEMIC DEBATE
-- =============================================================================

-- Table for Advanced Academic Debate
CREATE TABLE IF NOT EXISTS public.ai_tutor_stage6_exercise3_academic_debate (
    id SERIAL PRIMARY KEY,
    topic TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'C2',
    topic_type TEXT NOT NULL,
    controversy_level TEXT NOT NULL,
    expected_structure TEXT NOT NULL,
    expected_keywords TEXT[] NOT NULL,
    vocabulary_focus TEXT[] NOT NULL,
    academic_expressions TEXT[] NOT NULL,
    model_response TEXT NOT NULL,
    evaluation_criteria JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert data for Advanced Academic Debate
INSERT INTO public.ai_tutor_stage6_exercise3_academic_debate (topic, category, difficulty, topic_type, controversy_level, expected_structure, expected_keywords, vocabulary_focus, academic_expressions, model_response, evaluation_criteria) VALUES
('Should all education be free at all levels?', 'Education Policy', 'C2', 'Policy Debate', 'High', 'Thesis → Supporting Argument 1 → Supporting Argument 2 → Counterpoint → Conclusion', ARRAY['accessibility', 'equality', 'investment', 'quality', 'funding', 'opportunity', 'sustainability', 'responsibility', 'economic', 'social'], ARRAY['educational equity', 'socioeconomic barriers', 'human capital investment', 'fiscal responsibility', 'merit-based access', 'public investment', 'educational quality', 'economic sustainability', 'social mobility', 'academic excellence'], ARRAY['on the contrary', 'some argue that', 'it is worth considering', 'nevertheless', 'furthermore', 'in contrast', 'additionally', 'however', 'conversely', 'moreover'], 'I firmly believe that education should be free at all levels, as it represents the most effective investment in human capital and social progress. First, free education eliminates socioeconomic barriers that prevent talented individuals from reaching their potential, ensuring that merit rather than financial means determines educational access. This creates a more equitable society where opportunities are distributed based on ability and effort rather than economic privilege. Second, free education serves as a crucial driver of economic growth and innovation, as an educated workforce is essential for competing in the global knowledge economy. The long-term benefits of an educated population far outweigh the initial costs through increased productivity, reduced crime rates, and enhanced social cohesion. However, some argue that free education could lead to decreased quality and value perception, as people might not appreciate what they don''t pay for directly. While this concern has merit, the solution lies in maintaining rigorous academic standards and creating a culture that values education intrinsically. In conclusion, free education is not merely a social good but an economic imperative that benefits society as a whole.', '{"argument_structure": 30, "logical_flow": 25, "academic_expressions": 25, "critical_thinking": 20}'),
('Should governments limit access to social media platforms?', 'Digital Policy', 'C2', 'Regulation Debate', 'High', 'Thesis → Supporting Argument 1 → Supporting Argument 2 → Counterpoint → Conclusion', ARRAY['freedom', 'mental health', 'regulation', 'impact', 'privacy', 'misinformation', 'democracy', 'addiction', 'censorship', 'protection'], ARRAY['digital regulation', 'mental health implications', 'information dissemination', 'democratic discourse', 'privacy protection', 'misinformation control', 'digital addiction', 'freedom of expression', 'regulatory oversight', 'social media governance'], ARRAY['on the other hand', 'it is important to note', 'nevertheless', 'furthermore', 'in contrast', 'additionally', 'however', 'conversely', 'moreover', 'despite this'], 'I support implementing reasonable limitations on social media access, particularly for vulnerable populations, as the current unregulated environment poses significant risks to mental health and democratic discourse. First, social media platforms have been shown to contribute to mental health issues, particularly among young people, through mechanisms like social comparison, cyberbullying, and addictive design patterns that exploit psychological vulnerabilities. Second, the spread of misinformation and echo chambers on these platforms has demonstrably harmed democratic processes and social cohesion, making some form of regulatory oversight necessary for the public good. However, some argue that any government regulation of social media constitutes censorship and violates fundamental freedoms of expression. While this concern is valid, the distinction between reasonable regulation and censorship is crucial—we can implement safeguards against harmful content while preserving legitimate free speech. In conclusion, the goal should be balanced regulation that protects users without infringing on essential freedoms.', '{"argument_structure": 30, "logical_flow": 25, "academic_expressions": 25, "critical_thinking": 20}'),
('Is space exploration worth the massive financial investment required?', 'Scientific Investment', 'C2', 'Resource Allocation', 'Medium', 'Thesis → Supporting Argument 1 → Supporting Argument 2 → Counterpoint → Conclusion', ARRAY['investment', 'future', 'knowledge', 'resources', 'technology', 'survival', 'cost', 'discovery', 'innovation', 'priorities'], ARRAY['scientific advancement', 'technological innovation', 'human survival', 'resource allocation', 'scientific discovery', 'technological spin-offs', 'existential risks', 'scientific curiosity', 'economic investment', 'societal priorities'], ARRAY['it is worth considering', 'on the contrary', 'furthermore', 'in contrast', 'additionally', 'however', 'conversely', 'moreover', 'nevertheless', 'despite this'], 'I strongly believe that space exploration represents a crucial investment in humanity''s future, despite the substantial costs involved. First, space exploration drives technological innovation that benefits society in countless ways, from medical imaging technology to water purification systems, creating economic value that often exceeds the initial investment. Second, space exploration addresses fundamental questions about our place in the universe and provides insurance against existential risks, such as asteroid impacts or climate change, that could threaten human civilization. The knowledge gained from space exploration expands our understanding of physics, biology, and planetary science in ways that benefit all of humanity. However, some argue that the enormous costs of space exploration could be better spent addressing immediate problems on Earth, such as poverty, healthcare, and education. While these are indeed pressing concerns, the technological and scientific benefits of space exploration often provide solutions to terrestrial problems. In conclusion, space exploration is not a luxury but a necessity for human progress and survival.', '{"argument_structure": 30, "logical_flow": 25, "academic_expressions": 25, "critical_thinking": 20}'),
('Should artificial intelligence development be regulated by international law?', 'Technology Policy', 'C2', 'Global Governance', 'High', 'Thesis → Supporting Argument 1 → Supporting Argument 2 → Counterpoint → Conclusion', ARRAY['regulation', 'innovation', 'safety', 'competition', 'ethics', 'development', 'risks', 'benefits', 'control', 'progress'], ARRAY['AI governance', 'technological innovation', 'existential risks', 'ethical frameworks', 'competitive advantage', 'safety protocols', 'international cooperation', 'technological progress', 'regulatory oversight', 'responsible development'], ARRAY['on the other hand', 'it is important to note', 'nevertheless', 'furthermore', 'in contrast', 'additionally', 'however', 'conversely', 'moreover', 'despite this'], 'I support the implementation of international AI regulation, as the potential risks of unregulated artificial intelligence development far outweigh the benefits of unfettered innovation. First, AI systems pose unprecedented risks to human safety and autonomy, from autonomous weapons systems to AI systems that could potentially surpass human control, making coordinated international oversight essential for preventing catastrophic outcomes. Second, AI development affects global economic and social systems in ways that transcend national boundaries, requiring international cooperation to ensure equitable benefits and prevent harmful concentration of power. The development of AI governance frameworks can actually enhance innovation by creating clear ethical boundaries and safety standards that guide responsible development. However, some argue that international regulation would stifle innovation and give authoritarian regimes control over technological development, potentially creating competitive disadvantages for democratic nations. While this concern has merit, the solution lies in creating flexible regulatory frameworks that balance safety with innovation. In conclusion, international AI regulation is necessary to ensure that this transformative technology serves humanity''s best interests.', '{"argument_structure": 30, "logical_flow": 25, "academic_expressions": 25, "critical_thinking": 20}'),
('Are traditional schools becoming outdated in the digital age?', 'Education Evolution', 'C2', 'Educational Reform', 'Medium', 'Thesis → Supporting Argument 1 → Supporting Argument 2 → Counterpoint → Conclusion', ARRAY['online', 'flexibility', 'skills', 'discipline', 'socialization', 'technology', 'personalization', 'structure', 'interaction', 'adaptation'], ARRAY['educational innovation', 'digital transformation', 'personalized learning', 'social development', 'technological integration', 'educational flexibility', 'social interaction', 'academic discipline', 'learning outcomes', 'educational adaptation'], ARRAY['on the contrary', 'some argue that', 'it is worth considering', 'nevertheless', 'furthermore', 'in contrast', 'additionally', 'however', 'conversely', 'moreover'], 'I believe that traditional schools need significant transformation rather than complete replacement, as they still serve essential functions that digital alternatives cannot fully replicate. First, traditional schools provide crucial social development opportunities that are fundamental to human growth, including peer interaction, conflict resolution, and the development of emotional intelligence—skills that are increasingly valuable in our interconnected world. Second, the structured environment of traditional schools teaches important life skills such as discipline, time management, and working within systems, which are essential for success in most professional environments. The physical presence of teachers and peers creates accountability and motivation that online learning often lacks. However, some argue that traditional schools are too rigid and fail to adapt to individual learning needs, while digital platforms offer unprecedented personalization and flexibility. While this criticism has validity, the solution lies in integrating technology into traditional settings rather than replacing them entirely. In conclusion, the future of education should combine the best of both traditional and digital approaches.', '{"argument_structure": 30, "logical_flow": 25, "academic_expressions": 25, "critical_thinking": 20}');

-- =============================================================================
-- INDEXES FOR PERFORMANCE
-- =============================================================================

-- Indexes for Advanced Spontaneous Speaking
CREATE INDEX IF NOT EXISTS idx_spontaneous_speaking_category ON public.ai_tutor_stage6_exercise1_spontaneous_speaking(category);
CREATE INDEX IF NOT EXISTS idx_spontaneous_speaking_difficulty ON public.ai_tutor_stage6_exercise1_spontaneous_speaking(difficulty);
CREATE INDEX IF NOT EXISTS idx_spontaneous_speaking_topic_type ON public.ai_tutor_stage6_exercise1_spontaneous_speaking(topic_type);

-- Indexes for Advanced Diplomatic Communication
CREATE INDEX IF NOT EXISTS idx_diplomatic_communication_category ON public.ai_tutor_stage6_exercise2_diplomatic_communication(category);
CREATE INDEX IF NOT EXISTS idx_diplomatic_communication_difficulty ON public.ai_tutor_stage6_exercise2_diplomatic_communication(difficulty);
CREATE INDEX IF NOT EXISTS idx_diplomatic_communication_scenario_type ON public.ai_tutor_stage6_exercise2_diplomatic_communication(scenario_type);

-- Indexes for Advanced Academic Debate
CREATE INDEX IF NOT EXISTS idx_academic_debate_category ON public.ai_tutor_stage6_exercise3_academic_debate(category);
CREATE INDEX IF NOT EXISTS idx_academic_debate_difficulty ON public.ai_tutor_stage6_exercise3_academic_debate(difficulty);
CREATE INDEX IF NOT EXISTS idx_academic_debate_controversy_level ON public.ai_tutor_stage6_exercise3_academic_debate(controversy_level);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE public.ai_tutor_stage6_exercise1_spontaneous_speaking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_tutor_stage6_exercise2_diplomatic_communication ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_tutor_stage6_exercise3_academic_debate ENABLE ROW LEVEL SECURITY;

-- RLS Policies for public access (these are content tables, not user-specific)
CREATE POLICY "Anyone can view spontaneous speaking topics" ON public.ai_tutor_stage6_exercise1_spontaneous_speaking FOR SELECT USING (true);
CREATE POLICY "Anyone can view diplomatic communication scenarios" ON public.ai_tutor_stage6_exercise2_diplomatic_communication FOR SELECT USING (true);
CREATE POLICY "Anyone can view academic debate topics" ON public.ai_tutor_stage6_exercise3_academic_debate FOR SELECT USING (true);

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

-- Grant permissions for all tables
GRANT ALL ON public.ai_tutor_stage6_exercise1_spontaneous_speaking TO anon, authenticated;
GRANT ALL ON public.ai_tutor_stage6_exercise2_diplomatic_communication TO anon, authenticated;
GRANT ALL ON public.ai_tutor_stage6_exercise3_academic_debate TO anon, authenticated;

-- Grant permissions for sequences
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Verify data insertion
SELECT 'Advanced Spontaneous Speaking' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage6_exercise1_spontaneous_speaking
UNION ALL
SELECT 'Advanced Diplomatic Communication' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage6_exercise2_diplomatic_communication
UNION ALL
SELECT 'Advanced Academic Debate' as table_name, COUNT(*) as record_count FROM public.ai_tutor_stage6_exercise3_academic_debate;

-- Sample data verification
SELECT 'Sample Advanced Spontaneous Speaking:' as info;
SELECT id, topic, category, topic_type FROM public.ai_tutor_stage6_exercise1_spontaneous_speaking LIMIT 3;

SELECT 'Sample Advanced Diplomatic Communication:' as info;
SELECT id, scenario, category, scenario_type FROM public.ai_tutor_stage6_exercise2_diplomatic_communication LIMIT 3;

SELECT 'Sample Advanced Academic Debate:' as info;
SELECT id, topic, category, controversy_level FROM public.ai_tutor_stage6_exercise3_academic_debate LIMIT 3;
